- bin/upgrade/countly.github.update.sh
Allow dash usage in github update script
> Resolves #162

- api/api.js
I am not sure - i did not test, just made a small review
> [api] exited children did not restore correctly

- bin/countly.install.sh
Just one more minor tweak i found.
If it is not important, just discard :)
> Does not work in sudo-less instances

- api/parts/mgmt/jobs.js
Plugins lists concatenation will be in `pluginManager.getPlugins`
> Single source of data about plugins

- plugins/plugins/frontend/public/javascripts/countly.views.js
"enable"/"disable" filter can not work before.
> [plugins] fix path "/manage/plugins"  plugins "enable"/"disable" filter 

- frontend/express/public/localization/dashboard/dashboard_zh.properties
removed linebreak symbol which is unnecessary.
> removed linebreak symbol

- README.md
Fixed a spelling issue on line 30.
> Fix Spelling On ReadMe.md

- api/api.js
- frontend/express/app.js
Add a endpoint for usage within a load balancer to check api availability.
> add a endpoint "/ping" for health checking

- frontend/express/public/localization/dashboard/dashboard.properties
- frontend/express/public/stylesheets/main.css
- frontend/express/views/dashboard.html
Api key added to user dropdown menu top right.
> Place Api key also on user drop down menu.

- plugins/reports/api/api.js
- plugins/reports/api/reports.js
- plugins/reports/frontend/public/javascripts/countly.models.js
- plugins/reports/frontend/public/javascripts/countly.views.js
Changed validation method and added moment.js to report section for localization.
> Changed validation method and added moment.js to report section.

- frontend/express/views/dashboard.html
Added browser tooltip to app dropdownlist.
> Added browser tooltip to app dropdownlist.

- api/parts/mgmt/users.js
Added kill session method when a user password has changed from management/users panel
> Added kill session method to password change.

- frontend/express/public/javascripts/countly/countly.template.js
Regex special characters break dynamic regex text for the search area like "|". Added replace for these characters.
> Added escape for regex special characters.

- plugins/times-of-day/api/api.js
- plugins/times-of-day/frontend/app.js
- plugins/times-of-day/frontend/public/javascripts/countly.models.js
- plugins/times-of-day/frontend/public/javascripts/countly.views.js
- plugins/times-of-day/frontend/public/localization/times-of-day.properties
- plugins/times-of-day/frontend/public/stylesheets/main.css
- plugins/times-of-day/frontend/public/templates/times-of-day.html
- plugins/times-of-day/package.json
Times of day plugin for session and events visualization.
> Times of days plugin

- CONTRIBUTING.md
- Vagrantfile
> Quickly set up a dev env

- plugins/data_migration/api/api.js
- plugins/data_migration/api/data_migration_helper.js
- plugins/plugin-upload/frontend/app.js
plugin-upload - fixed bug
data-migration - fixed error msg logic, token passing
> plugin-upload, data-migration

- frontend/express/public/javascripts/countly/countly.helpers.js
fix percent of platformVersion issue
> fix percent of platformVersion

- api/api.js
- plugins/dbviewer/api/api.js
Both api endpoints can accepts filter or query, project or projection, db or dbs params now.
> Parameter intercompatability fixed between db viewer and export api.

- frontend/express/app.js
- frontend/express/views/forgot.html
- frontend/express/views/login.html
- frontend/express/views/reset.html
- frontend/express/views/setup.html
[SERVER-725]
Disable caching on pages with CSRF
> Disable caching on pages with CSRF

- frontend/express/public/javascripts/countly/countly.views.js
"Username doesn't change under drop-down menu when it is changed from Management > Users" issue has been fixed.
> Global username update problem.

- frontend/express/public/stylesheets/main.css
- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- plugins/dbviewer/frontend/public/stylesheets/main.css
- plugins/dbviewer/frontend/public/templates/dbviewer.html
Added a search box to top of collection list. #SERVER-722
> DB Viewer collection list improvements

- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- plugins/dbviewer/frontend/public/localization/dbviewer.properties
- plugins/dbviewer/frontend/public/templates/dbviewer.html
localization support to placeholder of search input.
> localization support to placeholder of search input.

- plugins/data_migration/api/data_migration_helper.js
FIXED bug checking recieved file type
> [plugins][data-migration]

- frontend/express/public/javascripts/countly/countly.event.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/localization/dashboard/dashboard.properties
- frontend/express/public/stylesheets/main.css
- frontend/express/views/dashboard.html
- test/2.api/15.event.managment.js
> [core] [SERVER-699][SEERVER-702], Changes, added tests

- frontend/express/public/javascripts/countly/countly.event.js
- frontend/express/public/javascripts/countly/countly.template.js
- plugins/assistant/frontend/public/javascripts/countly.models.js
- plugins/crashes/frontend/public/javascripts/countly.models.js
- plugins/locale/frontend/public/javascripts/countly.models.js
- plugins/sources/frontend/public/javascripts/countly.models.js
Issue fixed by cancelling requests, which are not for active view. Also calcelling unfinished requests on swiching between apps.
> view overlapping [SERVER-693]

- frontend/express/public/javascripts/countly/countly.template.js
requests aborting. fixed logic
> requests cancellation

- plugins/data_migration/api/data_migration_helper.js
- plugins/data_migration/frontend/public/javascripts/countly.views.js
- plugins/data_migration/tests/index.js
Fixed lists for data export. (Now taking from plugins.internelEvents and plugins.internalDrillEvents)Hiding checkbox for redirect if export and download. Fixed test timeout.
> [plugins][data-migration]Export tables.redirect checkbox.test timeout

- plugins/push/frontend/public/javascripts/countly.views.js
- plugins/push/frontend/public/localization/push.properties
- plugins/systemlogs/frontend/public/localization/systemlogs.properties
> [push]modify push menu in drill plugin

- frontend/express/public/javascripts/countly/countly.template.js
- plugins/assistant/frontend/public/javascripts/countly.views.js
- plugins/crashes/frontend/public/javascripts/countly.views.js
Fix applied to : crashes, assistant
> [SERVER-786] Prevent duplicate list loading

- api/parts/mgmt/app_users.js
- api/utils/requestProcessor.js
- plugins/data_migration/api/data_migration_helper.js
[plugins][data-migration] removed logging line
> [core]app_users saving exports in gridfs

- api/parts/mgmt/app_users.js
removed upsert:true on updating export status. 
If on successful export there is no record about user in db - clear out export. (If export takes long time - user might be deleted)
> [core] [app_users] changed upsert+remove export if user does not exist at end

- api/utils/requestProcessor.js
needed to fix bug in attribution plugin.
> [core][request] waiting for plugins.dispatch ("/i") to return promises

- api/api.js
- api/config.sample.js
- api/utils/requestProcessor.js
+Loading configs moved from api.js to requestProcessor.js
> [SERVER-785] [core] Loading config each minute(not on each request)

- plugins/plugin-upload/frontend/app.js
- plugins/plugin-upload/frontend/public/javascripts/countly.views.js
- plugins/plugin-upload/tests/index.js
> [SERVER-831] fixed issue by removing api.js requiring check

- plugins/plugins/api/api.js
- plugins/plugins/frontend/public/javascripts/countly.views.js
- plugins/plugins/frontend/public/localization/plugins.properties
- plugins/plugins/frontend/public/stylesheets/main.css
It's already working, I just created ui.
> User level configuration

- frontend/express/public/javascripts/countly/countly.event.js
- frontend/express/public/javascripts/countly/countly.views.js
-requests are made one after another(to don't run wrong data if switched)
-checking if data is loaded before refreshig
> [SERVER-823] [events] [bugfix] Data issue while navigating between events

- api/utils/requestProcessor.js
- frontend/express/public/javascripts/countly/countly.event.js
Fixed issue with not refreshing in overview and editing events
[SERVER-841] Changing event visibility bug
> events. bugfix. SERVER-841

- frontend/express/public/javascripts/countly/countly.event.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/stylesheets/main.css
- frontend/express/views/dashboard.html
1)added refresh fix
2)Small changes to allow notify revenue plugin about refreshed table
3)design fix to allow adding revenue column
> [SERVER-847] event blueprint

- frontend/express/public/stylesheets/main.css
- plugins/crashes/frontend/public/javascripts/countly.views.js
- plugins/slipping-away-users/frontend/public/javascripts/countly.views.js
update external table link
update slipping away plugin percentage UI component.
> [frontend] update  external table link layout

- frontend/express/public/javascripts/countly/countly.template.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/javascripts/dom/slimScroll.min.js
- frontend/express/public/stylesheets/main.css
fixed menu issue
Changed code - to don't hide scrollbar(default setting)
> [SERVER-827] No scroll UX

- frontend/express/app.js
- frontend/express/public/javascripts/pre-login.js
- frontend/express/public/localization/pre-login/pre-login.properties
- frontend/express/views/reset.html
"Force password complexity settings on password reset" issue has been fixed
> Force password complexity settings on password reset

- frontend/express/public/stylesheets/main.css
- fix semi-colon
- fix color property value
- add standart `animation` and `animation-iteration-count` property
> [frontend](style): css bugfix

- frontend/express/public/javascripts/countly/countly.common.js
- frontend/express/public/javascripts/countly/countly.helpers.js
- frontend/express/public/javascripts/countly/countly.session.js
- frontend/express/public/javascripts/countly/countly.views.js
- plugins/views/frontend/public/javascripts/countly.models.js
Removed sorting by value to display by order in bucket.
> [core][SERVER-912] Sort engagement graphs by bucket not by amount

- plugins/data_migration/api/api.js
- plugins/data_migration/api/data_migration_helper.js
- plugins/data_migration/frontend/public/javascripts/countly.views.js
fixed issue to always check for leading "/". 
When target folder given - all data is exported in target folder not only coppied.
> data migration fixes

- Gruntfile.js
- api/utils/requestProcessor.js
- bin/scripts/checking_versions.js
- frontend/express/public/javascripts/countly/countly.version.history.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/localization/dashboard/dashboard.properties
- frontend/express/views/dashboard.html
- plugins/data_migration/tests/index.js
-view to see countly versions(when it was upgraded)
-fixed data migration test output
-fixed version checking script to show warning not error.
> [SERVER-918] version history

- plugins/data_migration/api/api.js
- plugins/data_migration/api/data_migration_helper.js
- plugins/data_migration/tests/index.js
--fixed issue with redirect
--fixed tests for new changes
-- fixed to run import from any folder, clean up
> data-migration updates

- plugins/populator/frontend/public/javascripts/countly.models.js
> [data-populator] widget generate bug solved.

- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/stylesheets/main.css
- plugins/data_migration/frontend/public/stylesheets/main.css
- plugins/data_migration/frontend/public/templates/default.html
--rounded corners for side menu in views
--token manager - hiding record about current loggedinauth token, fixed table
--data migration - edit menu design fix
> design fixes

- plugins/star-rating/frontend/public/javascripts/countly.views.js
- plugins/star-rating/frontend/public/stylesheets/main.css
- target page style changed in widget row.
> [feedback] target_page style changed.

- api/utils/authorizer.js
- frontend/express/public/javascripts/countly/countly.token.manager.js
- frontend/express/public/javascripts/countly/countly.views.js
--  model comply with structure (err, data)
-- endpoint check fixed
--owner adding forced
> authorizer(Token manager) logic fixes

- plugins/star-rating/frontend/public/stylesheets/countly-feedback.css
- plugins/star-rating/frontend/public/templates/feedback-popup.html
- countly-feedback.css file formatted.
- popup tooltip font changed as 'Lato'.
> [feedback] popup tooltip style changes.

- api/parts/mgmt/app_users.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/stylesheets/main.css
- frontend/express/views/dashboard.html
- plugins/plugins/frontend/public/javascripts/countly.views.js
- plugins/systemlogs/frontend/public/localization/systemlogs.properties
[SERVER-959] AppManagement configs only show for Global admins
[SERVER-945] logging in starting app user export 
events bug when switching menu. styling
> styling, bugfixes

- plugins/pluginManager.js
Added extending feature if a user has already settings object for the related key.
> Fixed user level config bug.

- plugins/star-rating/frontend/public/stylesheets/countly-feedback-web.css
- plugins/star-rating/frontend/public/stylesheets/countly-feedback.css
- plugins/star-rating/frontend/public/stylesheets/main.css
- plugins/star-rating/frontend/public/templates/feedback-popup.html
- some little style conflicts resolved.
- app_version & sdk_name parameters supported by /feedback url now.
> [feedback] some css conflicts fixed & new query params for "/feedback" url

- plugins/populator/frontend/app.js
- [populator] required fs module.
> [populator] bugfix

- frontend/express/public/stylesheets/main.css
- frontend/express/views/dashboard.html
- plugins/data_migration/frontend/public/javascripts/countly.views.js
- plugins/data_migration/frontend/public/templates/export_drawer.html
- test/2.api/14.authorize.token.js
fix authorize test 
[SERVER-978] Migration - checkboxes are not aligned 
[SERVER-981] Events Overview - drawer button alignment bug
> Next design fixes

- plugins/populator/frontend/public/templates/demo-page.html
- plugins/star-rating/frontend/public/stylesheets/main.css
- demo-page request origin changed.
- search disabled on ratings tab.
> bugs fixed.

- plugins/dbviewer/frontend/public/stylesheets/main.css
- plugins/star-rating/frontend/public/stylesheets/countly-feedback-web.css
- plugins/star-rating/frontend/public/stylesheets/main.css
- dbviewer boxes height problem resolved.
- comment tab table rounded corner problem resolved.
> Style bugs fixed on dbviewer and feedback plugin.

- frontend/express/public/stylesheets/main.css
> [dashboard] overview bar style problem resolved.

- api/parts/mgmt/apps.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/stylesheets/main.css
New design
fixed issue to don't show link if it is not possible.
>  [SERVER-1015] New design for App Details popup 

- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- plugins/dbviewer/frontend/public/templates/dbviewer.html
- search bug fixed on "/manage/db/countly" path
- back button link wrapper moved up
> [dbviewer] manage database screen search bug resolved.

- frontend/express/public/javascripts/countly/countly.common.js
- plugins/data_migration/frontend/public/javascripts/countly.views.js
[SERVER-1024] Data migration - button behaviour bug 
[SERVER-1018] Crash - Sessions with a crash chart axis bug
>  [SERVER-1024] [SERVER-1018]  bugfix

- plugins/star-rating/frontend/public/stylesheets/main.css
big numbers(to be inline)
icon size
> star rating design fixes:

- plugins/browser/api/api.js
- plugins/browser/frontend/app.js
- plugins/browser/frontend/public/javascripts/countly.models.js
- plugins/browser/frontend/public/javascripts/countly.views.js
- plugins/compare/api/api.js
- plugins/compare/frontend/app.js
- plugins/compare/frontend/public/javascripts/countly.models.js
- plugins/compare/frontend/public/javascripts/countly.views.js
- plugins/density/api/api.js
- plugins/density/api/lib/countly.model.js
- plugins/density/frontend/app.js
- plugins/density/frontend/public/javascripts/countly.models.js
- plugins/density/frontend/public/javascripts/countly.views.js
- plugins/locale/api/api.js
- plugins/locale/api/lib/countly.model.js
- plugins/locale/api/utils/langs.js
- plugins/locale/frontend/app.js
- plugins/locale/frontend/public/javascripts/countly.models.js
- plugins/locale/frontend/public/javascripts/countly.views.js
- plugins/logger/api/api.js
- plugins/logger/frontend/app.js
- plugins/logger/frontend/public/javascripts/countly.models.js
- plugins/logger/frontend/public/javascripts/countly.views.js
- global variables declared at top of page
- loop indexes renamed
- compare operators changed as should be (!= -> !==)
- unused variables removed
> guidelines changes.

- plugins/server-stats/api/api.js
- plugins/server-stats/api/jobs/stats.js
- plugins/server-stats/frontend/app.js
- plugins/server-stats/frontend/public/javascripts/countly.models.js
- plugins/server-stats/frontend/public/javascripts/countly.views.js
> Guidelines improvements for server-stats plugin 

- frontend/express/public/javascripts/countly/countly.event.js
- frontend/express/public/javascripts/countly/countly.location.js
- frontend/express/public/javascripts/countly/countly.map.helper.js
- frontend/express/public/javascripts/countly/countly.session.js
- frontend/express/public/javascripts/countly/countly.task.manager.js
- frontend/express/public/javascripts/countly/countly.token.manager.js
guidelines fixes: countly.event.js, countly.location.js, countly.map.helper.js, countly.session.js, countly.task.manager.js, countly.token.manager.js
> guidelines fixes: countly.event.js, countly.location.js, countly.map.helper.js, countly.session.js, countly.task.manager.js, countly.token.manager.js

- frontend/express/public/javascripts/countly/countly.total.users.js
- frontend/express/public/javascripts/countly/countly.version.history.js
- frontend/express/public/javascripts/countly/countly.vue.components.js
countly.total.users.js, countly.version.history.js, countly.vue.components.js
> guideline fixes countly.total.users.js, countly.version.history.js, countly.vue.components.js

- plugins/server-stats/api/api.js
- plugins/server-stats/frontend/public/javascripts/countly.models.js
- api changes.
- frontend changes.
> [server-stats] 6 months, 12 months support.

- plugins/star-rating/api/api.js
> #SERVER-1156, #SERVER-1161

- Gruntfile.js
- frontend/express/public/javascripts/countly/countly.common.js
- frontend/express/public/javascripts/countly/countly.helpers.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/javascripts/utils/jquery.xss.js
- frontend/express/views/dashboard.html
Added function to partly encode html. Used function in popups.
> [SERVER-1127] Cross site scripting prevention.

- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/views/dashboard.html
- frontend/express/views/forgot.html
- frontend/express/views/login.html
- frontend/express/views/reset.html
- frontend/express/views/setup.html
[SERVER-1149] Referer header leackage 
[SERVER-1135] Omit event segments. prevent adding script.
>  [SERVER-1149] Referer header leackage,  [SERVER-1135] Omit event segments. prevent adding script.

- plugins/enterpriseinfo/frontend/public/stylesheets/pre-login.css
Fixed issue when scrollbar appears if recaptcha and enetprise plugin is enabled
> [SERVER-1177] Scrollbar when captcha is visible.

- frontend/express/app.js
Line 448:  If "login_tries" equal to zero then it means it's falsy so it sends 3 to bruteForce as a value
> Fixed bruteforce login attempd for zero value.

- frontend/express/public/javascripts/countly/countly.views.js
- prevented text highlights for clear data menu, clear data button and delete button.
> [server-1145] clear data button issues.

- frontend/express/public/localization/dashboard/dashboard.properties
- frontend/express/views/dashboard.html
- plugins/plugins/frontend/public/localization/plugins.properties
- plugins/plugins/frontend/public/templates/configurations.html
More clarification for Management > Apps and User Settings.
> [SERVER-1089] More clarification for Management > Apps and User Settings

- Vagrantfile
Modified Vagrantfile to provision development VM with 2048 MB memory.
> Fixes: #779, Modified Vagrantfile with higher VM memory.

- frontend/express/public/localization/dashboard/dashboard.properties
- plugins/mobile/frontend/public/javascripts/countly.views.js
- resolution bars changed as devices bars.
> [mobile-overview] mobile overview bar changed.

- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- plugins/dbviewer/frontend/public/stylesheets/main.css
- plugins/dbviewer/frontend/public/templates/dbviewer.html
- instead of refreshing whole view, fetching new needed data.
> [dbviewer] refresh optimization

- frontend/express/public/javascripts/countly/countly.views.js
- plugins/populator/frontend/public/javascripts/countly.views.js
- first app populate checkbox problem resolved.
- first_app flag disabler added for "not first app" situation.
> [first-app] first app populate checkbox problem resolved.

- Gruntfile.js
- frontend/express/public/javascripts/countly/countly.analytics.js
- frontend/express/views/dashboard.html
- plugins/desktop/frontend/public/javascripts/countly.views.js
- plugins/mobile/frontend/public/javascripts/countly.views.js
- plugins/web/frontend/public/javascripts/countly.views.js
- created countly.analytics.js library for generic getTop() method.
- integrated mobile, web and desktop plugins.
> [overview-bars] created generic getTop() method for overview screen and integrated plugins.

- plugins/systemlogs/api/api.js
- plugins/systemlogs/tests.js
> [SERVER-1272] Systemlogs changes comparison records too much, unchanged fields too

- plugins/times-of-day/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/javascripts/countly.views.js
- dashboard drawer six column support for times-of-day and views plugins.
> [dashboard-drawer] times-of-day and views plugin supports.

- plugins/star-rating/api/api.js
- added systemlogs for widget create, edit and remove processes.
> [ratings] added systemlogs for widget create, edit and remove processes.

- plugins/star-rating/frontend/public/javascripts/countly.views.js
- app version filter bug resolved.
> [app-version-filter] feedback app_version filter bug resolved.

- frontend/express/public/javascripts/countly/countly.helpers.js
- plugins/views/frontend/public/templates/views.html
[SERVER-1303] User profiles - Columns selector empty row bug
> [SERVER-1300] Views - cropped drill icon bugfix.

- api/parts/data/fetch.js
- frontend/express/public/javascripts/countly/countly.analytics.js
Changes in model (countly.analytics.js)- to fetch top only if period or app changed (not on every refresh call)
>  [SERVER-1319] Using aggregation query to calculate top three

- plugins/star-rating/frontend/public/javascripts/countly.views.js
- added "All pages" option for target_pages column in feedback widgets row.
- "target_page" value set "all" as default.
- "is_active" value set "true" as default
> [feedback-bug-fix] some ui bug fixes and improvements.

- plugins/dbviewer/api/api.js
- plugins/dbviewer/frontend/public/javascripts/countly.models.js
- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- added server-side pagination support to aggregation data-table.
- filter disabled.
> [dbviewer] server-side pagination for aggregation.

- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- aggregation object stringify removed.
> [aggregation-pipeline] export aggregation object stringfy removed.

- frontend/express/public/javascripts/countly/countly.event.js
- plugins/views/api/api.js
Views have incorrect url when sorting by other than view name
> [SERVER-1347] Bugfix

- plugins/dbviewer/frontend/public/javascripts/countly.models.js
- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- double request situation changed.
- aggregation process refactored.
> [aggregation-pagination] performance optimisations.

- frontend/express/public/javascripts/countly/countly.template.js
- frontend/express/public/javascripts/countly/countly.views.js
[SERVER-1351] Event Overview incorrectly formats duration - bug fixed 
[SERVER-1314] When datatable is empty, Drop throws error - bugfix, fixed
> Overview duration bug, drop error bug  - fixed

- frontend/express/app.js
- frontend/express/public/javascripts/countly/countly.city.js
- frontend/express/public/javascripts/countly/countly.location.js
- frontend/express/public/javascripts/countly/countly.map.helper.js
- plugins/plugins/frontend/public/javascripts/countly.views.js
- plugins/plugins/frontend/public/localization/plugins.properties
see https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code for more info
edit: oops, let's merge this into master instead of next
> migrate to new google charts loader

- frontend/express/views/dashboard.html
- plugins/crashes/frontend/public/templates/crash.html
Sorry, I missed a commit while cherry-picking from another branch to create #861. This is the hotfix for that.
> hotfix for missing google loader script link

- frontend/express/public/javascripts/countly/countly.helpers.js
- frontend/express/public/javascripts/countly/countly.template.js
- also added native keyboard navigate support for select option.
> [cly-select] added native tab behaivor to cly-select element.

- frontend/express/app.js
- frontend/express/public/localization/dashboard/dashboard.properties
- plugins/plugins/frontend/public/javascripts/countly.models.js
- plugins/plugins/frontend/public/javascripts/countly.views.js
- plugins/plugins/frontend/public/stylesheets/main.css
- plugins/plugins/frontend/public/templates/configurations.html
- plugins/systemlogs/frontend/app.js
- plugins/systemlogs/frontend/public/localization/systemlogs.properties
*created UI under  user settings.
*validates by user password
*last global admin can't be deleted
> Deleting own account functionality 

- api/parts/mgmt/app_users.js
- api/utils/taskmanager.js
Updated taskmanager.js to mark as errored if there is error at the end of task. Error message is also saved in DB.
> [SERVER-1407] Fixed issue with exiting process on error.

- frontend/express/public/javascripts/countly/countly.template.js
- set shouldRecordAction flag as false when extendSession method called.
- added error handler to ajax request.
> [SERVER-1383] Reduced session extend calls.

- api/utils/authorizer.js
- plugins/views/api/api.js
- plugins/views/frontend/public/javascripts/countly.views.js
1)Creates token only when clicking on link
2)Do not make new token - but extend it when getting actions (10 minutes)
3)Changes to authorizer to return also time after which token expires.
> [SERVER-1376] View action map increase expiration of token

- plugins/plugins/frontend/public/javascripts/countly.views.js
(for configurations created in plugins plugin)
>  [SERVER-1401] fixed bug with not displaying correct values in app level config after saving

- plugins/plugins/frontend/public/javascripts/countly.views.js
Fixing my broken commit 9ce0c84#diff-85abd6e08c87c2524c2678f1387ea756
> [[SERVER-1401]  Display correct values in app configuration after save

- frontend/express/public/javascripts/dom/slimScroll.min.js
--updated simScroll to newer version. Added to it changes we did previously.
> [SERVER-1422] Scroll slimScroll div with wheel when hovered, not whle page.

- bin/countly.install_rhel.sh
- bin/scripts/install-google-chrome.sh
- bin/scripts/install-python27.sh
- bin/scripts/install.nghttp2.sh
Fix #808 & update `countly.install_rhel.sh` to work properly on Centos/RHEL 6.x.
> Fix #808 & update Centos/RHEL 6.x support

- plugins/star-rating/api/api.js
- plugins/star-rating/frontend/public/javascripts/countly.models.js
- plugins/star-rating/frontend/public/javascripts/countly.views.js
- plugins/star-rating/frontend/public/stylesheets/countly-feedback-web.css
- plugins/star-rating/frontend/public/stylesheets/main.css
- plugins/star-rating/frontend/public/templates/star.html
- plugins/star-rating/tests.js
Fixed the following bugs and quirks in the star-rating plugin:
- Duplicate code in feedback model.
- Widget creation/editing modal straight up ignores toggling hide_sticker.
- In feedback widget creation modal, "Comment Callout" becomes "Add Comment" when you focus on its input.
- In feedback widget creation modal, inputs display html escaped content.
- After widget creation, the copy-paste code can't get the widget id right.
- In feedback widget creation modal, target pages doesn't get cleared after the modal goes away.
- Widget modal+backdrop+button aren't fixed to the screen so they don't move right with scrolling.
> [SERVER-1439] Feedback Fixes

- bin/commands/countly.sh
- bin/commands/scripts/add_user.sh
- bin/commands/scripts/decrypt.sh
- bin/commands/scripts/encrypt.sh
- bin/commands/scripts/mongo.sh
- bin/commands/scripts/remove_user.sh
Added necessary prompts to cli commands to prevent save sensitive informations in shell history.
> [server-1072] Exclude some countly commands from history

- plugins/crashes/frontend/public/javascripts/countly.views.js
- plugins/plugins/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/javascripts/countly.views.js
1) Changes to App configuration view to display drill settings
2) Changes to plugins "crashes" and "views" to use setting values when adding page script  on : "/drill#"
> [SERVER-1430] Make Drill configuration on app level

- api/parts/mgmt/users.js
- frontend/express/app.js
- frontend/express/config.sample.js
- frontend/express/libs/members.js
1)Added "passwordSecret" in frontend/express/config.sample.js (default empty string to don't break servers)
2)Made changes to use passwordSecret when creating and validating password.
> [SERVER-1406] Add password secret as config.js

- plugins/views/api/api.js
- plugins/views/frontend/public/javascripts/countly.models.js
Added functionality to check how many different views app has.
> [SERVER-1479] Views plugin. View count

- api/parts/mgmt/apps.js
- frontend/express/public/javascripts/countly/countly.views.js
- plugins/populator/frontend/public/localization/populator.properties
noticed this when locking a web app changed its type to mobile
edit: also added a fix for a link in app locking localizations
>  fixed app update validation overwriting with default values

- plugins/star-rating/frontend/public/stylesheets/countly-feedback-web.css
- media queries updated.
- svg icon alignments.
- radius problems solved for different place variations.
- and other little things.
> [ratings-style-fixes] some style fixes.

- bin/upgrade/19.07/scripts/migrate_totp.js
- bin/upgrade/19.07/upgrade_db.sh
- bin/upgrade/19.07/upgrade_fs.sh
I forgot to add it in the original PR :sweat_smile:
> [two-factor-auth] added upgrade script

- frontend/express/public/javascripts/countly/countly.helpers.js
(Wrong colspan because of hidden columns)
> Bugfix. Visual bug when loading user list with query.

- plugins/pluginManager.js
Also prevented turning numbers to strings.
> [SERVER-1460] Prevent turning strings into numbers in when changing configuration.

- frontend/express/public/stylesheets/main.css
The title of TopEvents widget must be uppercase. I forgot to commit this CSS line.
> [ui] top events title uppercase

- plugins/crashes/frontend/public/stylesheets/main.css
> [crash-style-fixes] crash three dot size changed.

- plugins/data_migration/api/data_migration_helper.js
Countly
blocked_users[APP_ID], crashes_jira[APP_ID], push_[APP_ID]
concurrent_users_max ( by appid + '_overall_new un appid + '_overall)
notes (by app_id)
top_events (by app_id)
Countly_out:
ab_testing_experiments[APP_ID]
remoteconfig_parameters[APP_ID]
remoteconfig_conditions[APP_ID]
>  Added collections to data migration.

- plugins/plugins/frontend/public/stylesheets/main.css
- user settings three dot icon resized.
- users screen dropdown alignment problem fixed.
> [settings-dropdown-arrow] some style fixes.

- plugins/data_migration/api/data_migration_helper.js
Exporting top_events - using app_d as object id
For import - import also countly_out
> data_migration

- frontend/express/public/javascripts/countly/countly.helpers.js
- frontend/express/public/stylesheets/main.css
- frontend/express/views/dashboard.html
Create global solution in CountlyHelper for creating and managing drawers
> [SERVER-1450] Creating drawers function in CountlyHelper

- frontend/express/public/javascripts/countly/countly.views.js
Also fixed similar issue in event management.
> [SERVER-1508] Bugfix. Events - keeping filtered events after changing segments.

- frontend/express/public/javascripts/countly/countly.views.js
- called applyColors() method in related places.
> [server-1504] countries screen color problem fixed.

- api/utils/requestProcessor.js
- frontend/express/public/javascripts/countly/countly.event.js
- frontend/express/public/javascripts/countly/countly.views.js
bugfix. requestProcessor.js i/tasks/name - calling correct function 
Fixed bugs for events.
1)Issue with hiding/showing event whan there is '.' in event name
2)Issue with matching events in frontend if their keys have special symbols like "&" in them.
3)Fixed related issue to 2 in event overview.
4)Fixed bug getting undefined _activeEvent in some situations.
> Bugfix. Events.

- plugins/views/api/api.js
- plugins/views/frontend/public/localization/views.properties
Fixed bug with incorrect values for two timestamp periods
Added validation when deleting view
> [SERVER-1533] View deletion added in systemlogs

- frontend/express/public/javascripts/countly/countly.common.js
> [SERVER-1543] Enterprise info plugin broken due to HTML stripping.

- frontend/express/public/javascripts/countly/countly.template.js
- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- plugins/dbviewer/frontend/public/templates/dbviewer.html
- created clearObjectId helper for handlerbars.
- added dynamic hrefs to related places.
> [server-1547] dbviewer links added.

- plugins/reports/api/reports.js
- plugins/reports/frontend/public/templates/email.html
> [SERVER-1593] update  report render logic for events & refactory data structure.

- plugins/pluginManager.js
In some situations, in the plugins manager, we may want to dispatch events to event handlers and be able to wait until they are all done processing, either successfully or faulty.
The function `allSettled` is an implementation of `Promise.allSettled` ([link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled)), available only from Node 12.9 however.
As soon as you upgrade to Node 12.9 or higher, you can replace the function `allSettled` by `Promise.allSettled` in `dispatchAllSettled` and delete functions `makeSettlePromise` and `allSettled`.
The implementation of `allSettled` I provide is compatible with `Promise.allSettled` in term of return value, meaning it returns an array of object that each contains a `status` property of type string …
> Allow dispatch of event handlers with Promise.allSettled in plugins manager

- frontend/express/public/javascripts/countly/countly.template.js
Modified function  app._removeUnfinishedRequests(); to clear also requests for views
Modification to call this function in all places where app is switched
> [SERVER-1549] Request Management and app switches - clearing unfinished requests on app switch

- plugins/alerts/frontend/public/localization/alerts.properties
- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- added "Enter alert name" to localization file.
> [alerts-localization] alerts localization changed.

- frontend/express/public/javascripts/visualization/flot/jquery.flot.spline.js
(To make line dashed, simply add  dashed:true to each series).
> Changes to draw dashed lines in graph. 

- bin/docker/k8s/countly-frontend.yaml
I think the image name in this k8 file is incorrect. Please take a look
> updating frontend image

- frontend/express/public/javascripts/countly/countly.common.js
- frontend/express/public/javascripts/visualization/flot/jquery.flot.spline.js
1)Fixed bug for tooltip. To use it's width (to don't have bug on wider tooltips)
2)Changed style for dashed line
> Graph changes (dashed line, tooltips)

- api/jobs/task.js
- api/utils/requestProcessor.js
- api/utils/taskmanager.js
- frontend/express/public/javascripts/countly/countly.views.js
Needed for [SERVER-1630]
[SERVER-1630]: https://countly.atlassian.net/browse/SERVER-1630
> Modification in task manager to support subtasks, show correct edit form for formulas and drill

- Gruntfile.js
- frontend/express/public/javascripts/countly/countly.common.js
- frontend/express/public/javascripts/visualization/flot/jquery.flot.js
- frontend/express/views/dashboard.html
This feature is implemented in two PRs across both editions. This part contains the changes related to the Community Edition components.
> [SERVER-1624] Y axis min/max and vertical pan in custom dashboard line & bar charts

- api/api.js
- api/utils/common.js
- bin/scripts/set_additional_api_configs.js
- bin/upgrade/dev/scripts/set_additional_api_configs.js
- frontend/express/app.js
> [server-1605] removed access origin headers and moved into config.

- frontend/express/public/javascripts/countly/countly.carrier.js
- frontend/express/public/javascripts/countly/countly.device.detail.js
- frontend/express/public/javascripts/countly/countly.device.js
- frontend/express/public/javascripts/countly/countly.location.js
- plugins/browser/frontend/public/javascripts/countly.models.js
- plugins/locale/frontend/public/javascripts/countly.models.js
- plugins/sources/frontend/public/javascripts/countly.models.js
Functions to get id's to match them in db from string.
Added for:
1) Devices (device name)
2) Device details (os version)
3) Location (country)
4) Carrier
5) Language
6) Sources
7)Browser version
> For [SERVER-1617] Big list and String input searching should do drill segment mapping

- bin/upgrade/dev/scripts/encrypt_2fa_secrets.js
- frontend/express/libs/members.js
- plugins/two-factor-auth/api/api.js
- plugins/two-factor-auth/frontend/app.js
1. Encrypt 2FA secrets in the database.
2. Let users retry instead of redirecting them to login when they are setting up 2FA for the first time or authenticating.
3. Try to use white label stuff for the TOTP QR code.
> [SERVER-1661] 2FA Improvements

- bin/scripts/mongodb.init.logrotate.sh
- bin/scripts/mongodb.install.sh
Using `dbPath` directive as reference for indent level.
> Fix [server-1691]

- plugins/data_migration/api/data_migration_helper.js
Bugfix to set data in messages collection after import.
Bugfix to correctly export credentials.
> Bugfixes to data migration

- plugins/views/tests.js
- plugins/web/api/api.js
- plugins/web/package.json
- plugins/web/tests.js
- new library implemented and added into package.json dependencies. (https://github.com/faisalman/ua-parser-js)
- useragent library removed from dependencies.
- added support for other app types (not only web type anymore.)
> [server-1659] changed useragent library.

- api/utils/authorizer.js
- bin/upgrade/dev/scripts/clearOldTokens.js
- frontend/express/app.js
- frontend/express/libs/members.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/localization/dashboard/dashboard.properties
[SEVER-1689] Reusing auth token. Clearing out expired each time new is created.
Duplicate clearing script for upgrade
Added timeout to /render token
>  [SEVER-1689] Reusing auth token. 

- api/parts/mgmt/users.js
- frontend/express/libs/members.js
[SERVER-1711] Deleting password reset requests when changing email in settings
[SERVER-1710] Old session does not invalidate after Password Reset
[SERVER-1711]: https://countly.atlassian.net/browse/SERVER-1711
[SERVER-1710]: https://countly.atlassian.net/browse/SERVER-1710
> Bugfix. Clearing sessions on password reset, reset requests on email change.

- api/parts/mgmt/apps.js
- api/utils/common.js
- frontend/express/app.js
Part of a fix for SERVER-1713 SERVER-1728.
> Sanitize filenames on upload endpoints

- api/utils/requestProcessor.js
- plugins/data_migration/api/data_migration_helper.js
- plugins/views/api/api.js
[SERVER-1739] Error when passing invalid list of id's on event deletion.
[SERVER-1738] Bugfix. data migration
[SERVER-1745] Bugfix. data migration
[SERVER-1736] Bugfix. views
[SERVER-1739]: https://countly.atlassian.net/browse/SERVER-1739
[SERVER-1738]: https://countly.atlassian.net/browse/SERVER-1738
[SERVER-1745]: https://countly.atlassian.net/browse/SERVER-1745
[SERVER-1736]: https://countly.atlassian.net/browse/SERVER-1736
> Small bugfixes in multiple places.

- api/utils/authorizer.js
- frontend/express/public/javascripts/countly/countly.common.js
[SERVER-1749] Fixed bug with wrong token owner
[SERVER-1733] Crashes graph has double dots
[SERVER-1749]: https://countly.atlassian.net/browse/SERVER-1749
[SERVER-1733]: https://countly.atlassian.net/browse/SERVER-1733
> [SERVER-1749] Fixed bug with wrong token owner [SERVER-1733] Crashes graph has double dots 

- frontend/express/public/javascripts/countly/countly.common.js
- frontend/express/public/localization/dashboard/dashboard.properties
- frontend/express/public/stylesheets/main.css
Adds zoom/pan to all time series graphs across Countly.
> [SERVER-1674] Zoom everything

- api/parts/mgmt/mail.js
- api/parts/mgmt/users.js
- frontend/express/app.js
- frontend/express/public/localization/mail/mail.properties
- frontend/express/public/localization/pre-login/pre-login.properties
- frontend/express/views/reset.html
SERVER-1724 After account creation to user is sent link with leads to password reset view.
SERVER-1729 escaping user provided values in all emails.
> Pentest email html injection, not sending pw after account creation.

- plugins/two-factor-auth/api/api.js
- plugins/two-factor-auth/frontend/app.js
- plugins/two-factor-auth/package.json
> [2fa] updated otplib

- frontend/express/public/javascripts/countly/countly.common.js
Function is created to check current graph type. Used in drawLineGraph function. If types don't match graph ir recreated.
> [SERVER-1774] Reset graph types.

- plugins/compliance-hub/frontend/public/javascripts/countly.views.js
- plugins/crashes/frontend/public/javascripts/countly.views.js
- reported consent ui load problem fixed.
- also I noticed same problem exist on crash tab and fixed that too.
> [server-1772] consent and crash tab problems fixed on user profile.

- plugins/populator/frontend/public/javascripts/countly.models.js
- plugins/populator/frontend/public/javascripts/countly.views.js
- plugins/populator/frontend/public/localization/populator.properties
This fixes both SERVER-1783 and SERVER-1784.
> [SERVER-1783] Populator templates fixes

- frontend/express/public/javascripts/countly/countly.common.js
Hopefully this will fix the cut off plots on zoom reset.
> [zoom] fixed pan reset behaviour

- plugins/star-rating/frontend/public/javascripts/countly.views.js
- plugins/star-rating/frontend/public/templates/star.html
- added type selector to modal opener.
> [feedback_fix] fixed integration popup problem.

- api/parts/data/exports.js
- frontend/express/public/javascripts/countly/countly.helpers.js
- frontend/express/views/dashboard.html
- package.json
[SERVER-1251] Streaming data exports to CSV and excel files
[SERVER-1251]: https://countly.atlassian.net/browse/SERVER-1251
> [SERVER-1251] Streaming data exports to CSV and excel files

- api/utils/taskmanager.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/stylesheets/main.css
++Updated styles for status dot to use same styling in token manager and report manager
> [SERVER-1830] Display errors in the report manager table .

- plugins/plugin-upload/frontend/public/javascripts/countly.views.js
Correct extension check for tar.gz
> Bugfix. Plugin-upload.

- plugins/populator/frontend/public/javascripts/countly.models.js
> [populator-template-duration-issue] fixed.

- frontend/express/public/javascripts/countly/countly.helpers.js
- frontend/express/public/javascripts/countly/countly.template.js
- frontend/express/public/localization/dashboard/dashboard.properties
- frontend/express/public/stylesheets/main.css
- frontend/express/views/dashboard.html
Currently used only in user profiles.
> [SERVER-1829] Allow to select which columns to export.

- bin/scripts/mongodb.install.sh
Change service type from 'forking' to 'simple' on SystemD service file of MongoDB to prevent SystemD timeout kill on service.
> Fix service type of mongodb on systemd

- api/utils/authorizer.js
- frontend/express/libs/members.js
[Needed for dashboards email reports]
> Bugfix. Allowing setting  temporary = true for token. If logged in with that token, on logout won't kill other sessions.

- frontend/express/public/javascripts/countly/countly.vue.components.js
- frontend/express/public/stylesheets/clyvue.css
- plugins/vue-example/frontend/public/javascripts/countly.models.js
- plugins/vue-example/frontend/public/javascripts/countly.views.js
- plugins/vue-example/frontend/public/templates/table.html
> [vue] DataTable improvements

- plugins/compliance-hub/api/api.js
- plugins/views/api/api.js
[SERVER-1882] Do not read views meta on requests that don't need it
[compliance hub] - update appUsers together with other appUsers updates
[SERVER-1882]: https://countly.atlassian.net/browse/SERVER-1882
> [compliance-hub] appUsers update, views - don't read meta if not needed

- api/parts/data/batcher.js
- plugins/times-of-day/api/api.js
Check saved projection on batcher to see if it has data currently needed
Times of day. Batching update. Reas batching call to 'events'
> Batcher - check projection. Times of day batching.

- plugins/views/api/api.js
- plugins/views/tests.js
> views - fixed dealing with duration,fixed Cly_action processing

- plugins/views/api/api.js
1)Moved app_viewsmeta estimatedDocument  to only call when needed.
2)Batch reads on app collection  on "/o/actions"
> Changes in views plugin

- api/lib/countly.common.js
- api/parts/data/fetch.js
- test/3.api.write/4.write.app.metrics.js
- test/3.api.write/6.bulk.write.js
> Tops. When calculating top N items, floor each and keep the rest for the first one

- plugins/star-rating/frontend/public/stylesheets/countly-feedback.css
- tested on chrome, safari and firefox.
> [server-1906] fixed.

- api/utils/taskmanager.js
- frontend/express/public/javascripts/countly/countly.task.manager.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/stylesheets/main.css
1)Added showing error messages also in automatic reports.
2)Showing error messages in table not only on hover(as before)
3)Updated task manager code to check server responses on task rerun and save errors.
4)Added message on errored tasks on restart.
> SERVER-1917 Report manager error messages.

- frontend/express/public/localization/dashboard/dashboard.properties
Quick addition for SERVER-1940.
> [SERVER-1940] renamed app-specific configs to settings

- plugins/star-rating/frontend/public/javascripts/countly.views.js
- plugins/star-rating/frontend/public/stylesheets/main.css
- decoded encoded strings before render.
- added length check for target pages.
> [feedback-ui-fixes] ui fixes.

- bin/commands/systemd/install.sh
- bin/commands/systemd/mongodb.sh
- bin/countly.install_rhel.sh
- bin/countly.install_ubuntu.sh
- bin/installer.sh
- bin/scripts/done.sh
- bin/scripts/mongodb.install.sh
Provide CentOS/RHEL 8 & Ubuntu 20 support(#1461) also drop support for CentOS/RHEL 6 & Ubuntu 16.
> CentOS/RHEL 8 & Ubuntu 20 support

- frontend/express/public/javascripts/countly/countly.event.js
- frontend/express/public/javascripts/countly/countly.views.js
(Update saved in db, but not visible in frontend)
Bug related to event keys having "." in them.
> BUGFIX. Fixed issue when updating event description doesn't work.

- api/parts/data/exports.js
- api/utils/requestProcessor.js
- frontend/express/public/javascripts/countly/countly.helpers.js
- frontend/express/public/localization/dashboard/dashboard.properties
- frontend/express/public/stylesheets/main.css
- frontend/express/views/dashboard.html
Allows to set options which states which fields need to be converted to string representing time.
Created backend function which fixes fields if chosen.
> [SERVER-1980] Exported files to have date format, not timestamp

- api/parts/data/cache.js
- plugins/push/api/api.js
- plugins/push/api/parts/endpoints.js
- plugins/push/api/parts/note.js
- plugins/push/api/parts/store.js
- plugins/push/frontend/public/javascripts/component.emoji.js
- plugins/push/frontend/public/javascripts/component.push.dash.js
- plugins/push/frontend/public/javascripts/component.push.js
- plugins/push/frontend/public/javascripts/component.push.popup.js
- plugins/push/frontend/public/javascripts/component.push.view.js
- plugins/push/frontend/public/javascripts/component.singleselect.js
- plugins/push/frontend/public/localization/push.properties
- plugins/push/frontend/public/stylesheets/main.css
SERVER-2095
SERVER-2015
FEAT-58
SERVER-1911
> [push] Adding event segmentation as personalization options

- plugins/views/scripts/fixViews.js
- plugins/views/scripts/renameViews.js
Added scripts for views renaming and mergin/fixing indexes
> Views. Scripts.

- api/utils/taskmanager.js
To see - add  core:taskmanager to lgging debug in  settings.
> debbuging for rerunning tasks.

- plugins/sources/api/api.js
- plugins/sources/package.json
Reverts Countly/countly-server#1715
> Revert "[SERVER-2079]"

- plugins/views/api/api.js
Recoding exit, bounce and duration for drill
1)Fixed bug for recording duration two times in some cases(if no visit then only call dispatch)
2)Dispatch updating drill record on session/post for bounce and exit
> BUGFIX - views

- frontend/express/public/javascripts/countly/countly.template.js
SERVER-1930 breaks some datepicking functionality and causes random errors (for instance in drill).This reverts SERVER-1930 altogether.
> SERVER-2144

- api/parts/data/exports.js
Updated export function to flatten first level of array and stringify each value in case each item in array is array or object
> [SERVER-2085] BUG - exporting surveys data appear as [object Object],[object Object] values.

- plugins/crashes/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/javascripts/countly.views.js
I simply applied the star-rating's solution: https://github.com/Countly/countly-server/commit/b3ad261817bdf5a0ca04f92fa2e1ac2de6d67d1a
> SERVER-2151

- plugins/dbviewer/api/api.js
- plugins/dbviewer/frontend/public/javascripts/countly.models.js
- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- plugins/dbviewer/frontend/public/localization/dbviewer.properties
- plugins/dbviewer/frontend/public/stylesheets/main.css
- plugins/dbviewer/frontend/public/templates/dbviewer.html
- plugins/dbviewer/frontend/public/templates/table.html
1. Added two new buttons in dbviewer plugin mongotop and mongostat.
2. Impemented api changes for the same.
3. Modified client side code to render data for mongotop and mongostat.
4. Modified css to display mongostat and mongotop data in form of a table.
> SERVER-2141 -> Adding Mongotop and Mongostat to DBViewer

- api/parts/data/exports.js
For cases when requests need longer than minute to calculate data
> Added "Keeping alive function" when exporting from request. 

- plugins/two-factor-auth/frontend/public/javascripts/countly.views.js
Instead of arbitrarily waiting 250ms for binding an event callback for an element that might be there, bind it to its parent which will definitely be there, and let the event bubble up.
> [2fa] fixed "disable 2fa" buttons sometimes not showing up in users view

- api/parts/data/exports.js
- api/utils/requestProcessor.js
- api/utils/taskmanager.js
- frontend/express/public/javascripts/countly/countly.helpers.js
- frontend/express/public/javascripts/countly/countly.task.manager.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/localization/dashboard/dashboard.properties
- plugins/views/api/api.js
- plugins/views/frontend/public/javascripts/countly.views.js
*added new feature - requestQuery. Plugin gives aggregation pipeline, collection name and dbname.
*result goes to report manager.
*exports runs query, gets result, streams that via transformation function into filesystem.
*After there is notification about download.
> Changes to views table export

- Gruntfile.js
- package.json
Also added `grunt watch`, it watches scss files and compiles them automatically.
> Added plugins to grunt sass targets

- api/jobs/topEvents.js
- api/lib/countly.model.js
- api/parts/data/fetch.js
1. Changed top_events schema.
2. Modified api to fetch events based on count, sum, duration.
> SERVER-2223 Changes for Events Overview

- bin/dev-scripts/install-pre-commit-hooks.sh
> Fixed pre-commit script

- plugins/plugins/frontend/app.js
- plugins/plugins/frontend/public/javascripts/countly.views.js
api domain configuration provided automatically.
> SERVER-2283: Set api.domain in settings automatically.

- api/parts/mgmt/users.js
- api/utils/rights.js
- added undefined checks to getAminApps and getUserApps methods.
- removed unnecessary lines from getAllUsers().
> [right.js-fix] added undefined check to hasAdminAccess()

- frontend/express/public/javascripts/countly/vue/components/helpers.js
Added prop for number classes in cly-metric-card
> Added prop for number classes in cly-metric-card

- plugins/sources/frontend/public/javascripts/countly.views.js
- plugins/sources/frontend/public/localization/sources.properties
- plugins/sources/frontend/public/stylesheets/sources.scss
- plugins/sources/frontend/public/templates/extend-table.html
- plugins/sources/frontend/public/templates/keywords-tab.html
- plugins/sources/frontend/public/templates/main.html
- plugins/sources/frontend/public/templates/sources-tab.html
vue transition of "Sources" and "Search Terms" views.
> vue transition of "Sources" and "Search Terms" views.

- frontend/express/public/core/geo-countries/javascripts/countly.cities.models.js
- frontend/express/public/core/geo-countries/javascripts/countly.models.js
- frontend/express/public/core/geo-countries/javascripts/countly.views.js
- frontend/express/public/core/geo-countries/stylesheets/_main.scss
- frontend/express/public/core/geo-countries/templates/cities.html
- frontend/express/public/core/geo-countries/templates/countries.html
- frontend/express/public/core/geo-countries/templates/geo-analytics.html
- frontend/express/public/core/platform/javascripts/countly.views.js
- frontend/express/public/javascripts/countly/countly.views.js
- frontend/express/public/localization/dashboard/dashboard.properties
- frontend/express/public/stylesheets/styles/manifest.scss
- frontend/express/views/dashboard.html
- plugins/desktop/frontend/public/javascripts/countly.views.js
- plugins/locale/frontend/public/javascripts/countly.models.js
- plugins/locale/frontend/public/javascripts/countly.views.js
- plugins/locale/frontend/public/stylesheets/main.css
- plugins/locale/frontend/public/templates/language.html
- plugins/mobile/frontend/public/javascripts/countly.views.js
- plugins/web/frontend/public/javascripts/countly.views.js
*Added countries tab
*Added language tab
*Edited menu to have geo tab
*removed old countries from analytics
> Geo section in analytics.

- frontend/express/public/javascripts/countly/vue/components/helpers.js
- frontend/express/public/javascripts/countly/vue/components/input.js
- frontend/express/public/javascripts/countly/vue/templates/worldmap.html
- frontend/express/public/stylesheets/styles/blocks/_helpers.scss
Fixed / enchanced stuff I ran into while working on Activity Map :blossom:
> Worldmap Additions

- frontend/express/public/javascripts/countly/vue/components/helpers.js
- frontend/express/public/javascripts/countly/vue/components/input.js
- frontend/express/public/javascripts/countly/vue/templates/selectx.html
As per @itsiprikshit's request :innocent:
> [frontend] added popClass prop to select-x to pass to its dropdown child

- frontend/express/libs/members.js
Add method createMember to memberUtils for external authentication providers like AD, LDAP, OKTA, COGNITO
> create members for external auth provider

- plugins/browser/frontend/public/javascripts/countly.views.js
- plugins/browser/frontend/public/templates/browser.html
> added external link for drill

- plugins/views/frontend/public/javascripts/countly.models.js
- plugins/views/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/templates/manageViews.html
- plugins/views/frontend/public/templates/views.html
1)Using  cly-diff-helper for name changes in manage views
2)Fixed column width for main table
3)Added column selector for main table.
4)Auto selection of top 5 views if none selected.
5)Fixed default sort
6)Fixed number formating for top values
> Fixes for new UI/views.

- plugins/sources/frontend/public/javascripts/countly.views.js
- plugins/sources/frontend/public/templates/sources-tab.html
> Added drill plugin control

- plugins/sources/frontend/public/localization/sources.properties
- plugins/sources/frontend/public/templates/sources-tab.html
> Added key to localization.

- frontend/express/public/javascripts/countly/vue/components/sidebar.js
- frontend/express/public/javascripts/countly/vue/core.js
- frontend/express/public/javascripts/countly/vue/templates/sidebar/AppSelector.html
- frontend/express/public/javascripts/countly/vue/templates/sidebar/analytics-menu.html
- frontend/express/public/javascripts/countly/vue/templates/sidebar/users-menu.html
- frontend/express/public/stylesheets/styles/blocks/_sidebar.scss
WIP: Kindly ignore inline css and linting error
> WIP: Custom selector for app selection

- frontend/express/public/core/events/templates/configureEvents.html
- frontend/express/public/core/events/templates/overview.html
Check on overview page when topEvents are empty(Cron has not yet run)
> Check on overview page when topEvents are empty

- frontend/express/public/core/events/javascripts/countly.details.models.js
- plugins/compare/frontend/public/javascripts/countly.models.js
- plugins/compare/frontend/public/localization/compare.properties
- plugins/compare/frontend/public/templates/compare.html
Positioning of legend on compare events
> Positioning of legend on compare events

- frontend/express/public/javascripts/countly/vue/container.js
> core. vue.

- plugins/browser/frontend/public/stylesheets/browser.scss
- plugins/browser/frontend/public/templates/browser.html
> fixed visual bugs

- plugins/sources/frontend/public/localization/sources.properties
- plugins/sources/frontend/public/templates/keywords-tab.html
> fixed tooltip descriptions

- frontend/express/public/core/app-resolution/javascripts/countly.views.js
- frontend/express/public/core/app-resolution/templates/app-resolution.html
- frontend/express/public/core/app-version/javascripts/countly.views.js
- frontend/express/public/core/carrier/javascripts/countly.views.js
- frontend/express/public/core/device-and-type/javascripts/countly.views.js
- frontend/express/public/core/device-and-type/templates/devices-tab.html
- frontend/express/public/core/device-and-type/templates/types-tab.html
- frontend/express/public/core/platform/javascripts/countly.views.js
- frontend/express/public/core/platform/templates/platform.html
- frontend/express/public/localization/dashboard/dashboard.properties
*resolution titles
*devices and types titles
*Formatting for center of pie graph
*Formatting in platforms
> Technology fixes:

- api/utils/requestProcessor.js
- api/utils/rights.js
- frontend/express/app.js
- frontend/express/public/core/user-management/javascripts/countly.models.js
- frontend/express/public/core/user-management/javascripts/countly.views.js
- added global_upload feature type for upload processes.
> [user-management-fixes] fixed some core and ui problems.

- frontend/express/public/core/app-management/javascripts/countly.views.js
And watch settings object for dynamic app settings
> [apps] management manipulate sidebar on app changes

- frontend/express/public/javascripts/countly/vue/components/helpers.js
- frontend/express/public/stylesheets/vue/clyvue.scss
css changes for cly-empty-home
> css changes for cly-empty-home

- frontend/express/public/core/events/javascripts/countly.details.models.js
- frontend/express/public/core/events/javascripts/countly.details.views.js
- frontend/express/public/core/events/templates/allEvents.html
Integrated data manager api and added category for events
> SERVER-2222 Added category for events

- plugins/star-rating/api/api.js
return moved to outside of the calculateSteps.
> [ratings-cohort-bug-fix] api changes.

- api/parts/data/exports.js
Updated to allow PUSH plugin modify query to get result.
> Bugfix. Exported file do not limit users on query: Recieved message is #.

- frontend/express/public/javascripts/countly/vue/components/vis.js
- frontend/express/public/localization/dashboard/dashboard.properties
- plugins/views/api/api.js
> Feature/new UI

- frontend/express/public/images/icons/empty-view-icon.svg
- frontend/express/public/javascripts/countly/vue/components/helpers.js
- frontend/express/public/javascripts/countly/vue/templates/datatable.html
- frontend/express/public/localization/dashboard/dashboard.properties
- frontend/express/public/stylesheets/vue/clyvue.scss
These changes include [SERVER-2431]: "Table/header should be fixed at the top" and [SERVER-2418]: Data table-empty state
[SERVER-2431]: https://countly.atlassian.net/browse/SERVER-2431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SERVER-2418]: https://countly.atlassian.net/browse/SERVER-2418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SERVER-2418]: Data table-empty state

- plugins/push/frontend/public/javascripts/countly.models.js
- plugins/push/frontend/public/javascripts/countly.views.js
- plugins/push/frontend/public/templates/common-components.html
- plugins/push/frontend/public/templates/push-notification-tab.html
Dashboard data will not be refreshed, only push notification rows.
Fix: 
- Consider info object as optional and add short circuit operator until server validation is fixed.
- Template tag for add user property popup.
> feature: Separate fetching dashboard and all push notifications

- frontend/express/public/core/app-resolution/templates/app-resolution.html
- frontend/express/public/core/app-version/templates/app-version.html
- frontend/express/public/core/device-and-type/templates/devices-and-types.html
- frontend/express/public/core/geo-countries/templates/countries.html
- frontend/express/public/core/platform/templates/platform.html
- frontend/express/public/core/session-durations/templates/session-durations.html
- frontend/express/public/core/session-frequency/templates/session-frequency.html
- frontend/express/public/core/session-overview/templates/session-overview.html
- frontend/express/public/core/user-activity/templates/user-activity.html
- frontend/express/public/core/user-analytics-overview/templates/overview.html
- frontend/express/public/javascripts/countly/vue/components/progress.js
- frontend/express/public/javascripts/countly/vue/components/vis.js
- frontend/express/public/stylesheets/styles/blocks/_progress.scss
- plugins/browser/frontend/public/templates/browser.html
- plugins/density/frontend/public/templates/density.html
- plugins/locale/frontend/public/templates/language.html
- plugins/slipping-away-users/frontend/public/templates/slipping-away-users.html
- plugins/sources/frontend/public/templates/keywords-tab.html
- plugins/sources/frontend/public/templates/sources-tab.html
- plugins/times-of-day/frontend/public/templates/times-of-day.html
- plugins/views/frontend/public/templates/views-per-session.html
- plugins/views/frontend/public/templates/views.html
tooltip component fixes to specified locations
> Fixed visitor loyalty css changes

- frontend/express/public/core/platform/templates/platform.html
- frontend/express/public/javascripts/countly/vue/components/helpers.js
- frontend/express/public/stylesheets/vue/clyvue.scss
- plugins/browser/frontend/public/templates/browser.html
- plugins/density/frontend/public/templates/density.html
- plugins/heatmaps/frontend/public/templates/index.html
- plugins/push/frontend/public/templates/push-notification-tab.html
- plugins/sources/frontend/public/templates/keywords-tab.html
- plugins/views/frontend/public/templates/views.html
- plugins/vue-example/frontend/public/templates/metric-cards.html
> [SERVER-2456]: CSS fixes of metric cards

- frontend/express/public/javascripts/countly/countly.template.js
- plugins/server-stats/api/api.js
- plugins/server-stats/api/parts/stats.js
- plugins/server-stats/frontend/public/javascripts/countly.models.js
- plugins/server-stats/frontend/public/javascripts/countly.views.js
- plugins/server-stats/frontend/public/localization/server-stats.properties
- plugins/server-stats/frontend/public/stylesheets/main.css
- plugins/server-stats/frontend/public/templates/data-points.html
fix for duplicate request cancellation
> fixes for data points

- plugins/push/frontend/public/javascripts/countly.models.js
- plugins/push/frontend/public/javascripts/countly.views.js
- plugins/push/frontend/public/templates/push-notification-tab.html
Add delete push notification action for details page.
Update table loading state when user command is taking place.
Format: todo notes about logging errors in the model
> fix: Deleting push notification from details page error

- frontend/express/public/javascripts/countly/vue/components/layout.js
Instead of validator check for backlink properties inside the template rendering.
> fix: Backlink prop error assuming it is required

- frontend/express/public/javascripts/countly/vue/components/dropdown.js
- frontend/express/public/javascripts/countly/vue/components/layout.js
- plugins/data-manager/frontend/public/javascripts/countly.views.js
- plugins/data-manager/frontend/public/stylesheets/main.scss
- plugins/data-manager/frontend/public/templates/create-event-drawer-components.html
- plugins/data-manager/frontend/public/templates/create-events-drawer.html
- plugins/data-manager/frontend/public/templates/event-detail.html
- plugins/data-manager/frontend/public/templates/event-group-detail.html
- plugins/data-manager/frontend/public/templates/event-group-drawer.html
- plugins/data-manager/frontend/public/templates/event-groups.html
- plugins/data-manager/frontend/public/templates/events-default.html
- plugins/data-manager/frontend/public/templates/events.html
- plugins/data-manager/frontend/public/templates/manage-category-components.html
remove else for header when backlink is shown.
added styling classes
> fix for header with backlink

- plugins/data-manager/frontend/public/javascripts/countly.models.js
- plugins/data-manager/frontend/public/javascripts/countly.views.js
suppress error on quick tab change/autocatch
> Fix transformation edit bug

- plugins/star-rating/api/api.js
- plugins/star-rating/frontend/public/stylesheets/ratings-iframe.scss
- plugins/star-rating/frontend/public/stylesheets/ratings-sdk.scss
- changed behaviour of ratings api for cases targeting column comes as null.
- also some css changes for feedback popup.
> [ratings-targeting-fixes] changed behaviour of ratings api.

- plugins/data_migration/frontend/public/javascripts/countly.views.js
these should not be exist anymore, because we already use auth mixin.
> removed unnecessary validation states.

- plugins/views/api/api.js
- plugins/views/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/templates/widgetDrawer.html
a)Placed under analytics
b)Using dashboards components
> fixed views widget:

- plugins/server-stats/frontend/public/templates/data-points.html
* removed top metric cards for subpage
* removed links in tabl for subpage
> [SERVER-2544] Design fixes for data points subpage

- frontend/express/public/core/device-and-type/javascripts/countly.views.js
- frontend/express/public/core/device-and-type/templates/widgetDrawer.html
- frontend/express/public/core/geo-countries/javascripts/countly.widgets.geo.js
- frontend/express/public/core/geo-countries/templates/dashboard-widget/drawer.html
- frontend/express/public/core/user-analytics-overview/javascripts/countly.views.js
- frontend/express/public/javascripts/countly/vue/core.js
- plugins/dashboards/api/parts/dashboards.js
- plugins/dashboards/frontend/public/javascripts/countly.helpers.js
- plugins/dashboards/frontend/public/javascripts/countly.views.js
- plugins/dashboards/frontend/public/javascripts/countly.widgets.analytics.js
- plugins/dashboards/frontend/public/localization/dashboards.properties
- plugins/dashboards/frontend/public/stylesheets/main.scss
- plugins/dashboards/frontend/public/templates/helpers/widget/appPeriod.html
- plugins/dashboards/frontend/public/templates/widget.html
- plugins/dashboards/frontend/public/templates/widgets/analytics/widget.html
- plugins/sources/frontend/public/javascripts/countly.views.js
- plugins/sources/frontend/public/templates/widgetDrawer.html
- plugins/views/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/localization/views.properties
*analytics/views widget
*analytics/geo widget
*analytics/technology widget
*analytics/users/overview widget
> Analytics widget

- frontend/express/public/javascripts/countly/vue/core.js
- plugins/dashboards/frontend/public/javascripts/countly.helpers.js
- plugins/views/frontend/public/javascripts/countly.models.js
- plugins/views/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/localization/views.properties
- plugins/views/frontend/public/templates/views.html
Changes for views plugin to allow listing all "selected"
> fixes for views

- plugins/star-rating/api/api.js
- plugins/star-rating/frontend/public/javascripts/countly.views.js
- also added replace for escaped characters on client-side.
> [sdk-ratings-widget-name] added name prop to ratings widgets feed api.

- frontend/express/public/core/report-manager/javascripts/countly.views.js
- plugins/views/frontend/public/heatmap.js
- plugins/views/frontend/public/stylesheets/heatmap.css
Also added data-manger to report manager
> heatmap css changes

- frontend/express/public/core/device-and-type/javascripts/countly.views.js
- frontend/express/public/core/geo-countries/javascripts/countly.widgets.geo.js
- frontend/express/public/core/user-analytics-overview/javascripts/countly.views.js
- plugins/dashboards/frontend/public/javascripts/countly.widgets.note.js
- plugins/dashboards/frontend/public/localization/dashboards.properties
- plugins/dashboards/frontend/public/templates/widgets/note/drawer.html
- plugins/dashboards/frontend/public/templates/widgets/note/widget.html
- plugins/push/api/api-message.js
- plugins/sources/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/javascripts/countly.views.js
preloading templates for analytics widgets
Added text-align styling for note widget
> Fixes for analytics widgets 

- frontend/express/public/core/session-overview/javascripts/countly.views.js
- plugins/dashboards/frontend/public/javascripts/countly.helpers.js
- plugins/dashboards/frontend/public/javascripts/countly.widgets.note.js
- plugins/dashboards/frontend/public/templates/helpers/widget/appPeriod.html
- plugins/dashboards/frontend/public/templates/widgets/note/widget.html
- plugins/views/api/api.js
- plugins/views/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/templates/manageViews.html
- plugins/views/frontend/public/templates/views.html
[SERVER-2547] Hiding delete or/and edit buttons based on user permisons in Views
Setting correct permission checks at backend.
Dashboards. fixes for notes widget and period helper
Home. prevent showing previous app values on session graph on app switch.
[SERVER-2547]: https://countly.atlassian.net/browse/SERVER-2547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixes for new UI. Views. Dashboards. Home

- frontend/express/public/localization/dashboard/dashboard.properties
- plugins/views/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/stylesheets/main.css
- plugins/views/frontend/public/templates/views.html
*Adjust limit button in views
*% for bounce rate
> Bugfixes views

- plugins/sources/frontend/public/javascripts/countly.views.js
- plugins/sources/frontend/public/templates/sourcesHomeWidget.html
- plugins/views/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/templates/views.html
*Sources home widget - added "no data" text on no sources
*Keywords home widget - fixed bug happening  if  0<keyword count<3
*Adding loading circle on graph in views
> New UI bugfixes [Home-sources][Home-keywords][Views]

- bin/upgrade/dev/scripts/group_permission_generator.js
- bin/upgrade/dev/scripts/member_permission_generator.js
also removed global_admin flag from query.
> [permission-scripts] created group permission generator.

- plugins/dbviewer/frontend/public/stylesheets/main.scss
- plugins/dbviewer/frontend/public/templates/aggregate.html
- plugins/dbviewer/frontend/public/templates/tab.html
- id on the tab rows are vertically aligned.
- document detail modal title changed.
> [dbviewer-style-changes] added dummy columns to aggregation table.

- plugins/star-rating/frontend/app.js
> [ratings-popup-backward] added old endpoint for backward compatability.

- plugins/dashboards/frontend/public/stylesheets/main.scss
- plugins/dashboards/frontend/public/templates/widgets/note/widget.html
*hiding 3-dot button on hover
*positioning it over.
> Dashboards notes widget.

- frontend/express/public/core/user-management/javascripts/countly.views.js
- frontend/express/public/localization/dashboard/dashboard.properties
- this change converted read permission a dependency for all other permission types like create, update, delete.
> permission dependencies.

- plugins/dashboards/api/parts/dashboards.js
- plugins/dashboards/frontend/public/javascripts/countly.widgets.events.js
Fetching event display name for cases title is not set
> Dashboards. events widget.

- plugins/dashboards/api/parts/dashboards.js
- plugins/dashboards/frontend/public/javascripts/countly.widgets.events.js
- plugins/views/api/api.js
- plugins/views/frontend/public/javascripts/countly.models.js
- plugins/views/frontend/public/javascripts/countly.views.js
- plugins/views/tests.js
Dashboard event widget
- Show event group name
Views.
- Hide empty views rows on table fetch
-Showing error message in dashboard un unsuccessful view edit/delete
> Dashboards events widget. Views

- frontend/express/public/core/device-and-type/templates/devices-tab.html
- frontend/express/public/core/device-and-type/templates/types-tab.html
- plugins/crashes/frontend/public/javascripts/countly.views.js
- plugins/crashes/frontend/public/localization/crashes.properties
- plugins/crashes/frontend/public/templates/crashesHomeWidget.html
- plugins/locale/api/api.js
- plugins/locale/frontend/public/javascripts/countly.models.js
- plugins/locale/frontend/public/javascripts/countly.views.js
- plugins/locale/frontend/public/templates/language.html
Analytics/Technology-devices
- Swapped sides for graphs
Crashes
- Correct localization in home
Languages
- Added loading circle
- Number formatting in table
- Swapped sides for graphs
> Fixes. Languages   Crashes/Home   Analytics/Technology/Devices

- plugins/push/frontend/public/javascripts/countly.models.js
- plugins/push/frontend/public/templates/push-notification-app-config.html
Replace id with device id for test users.
> fix: Test user id error

- plugins/browser/frontend/public/javascripts/countly.views.js
- plugins/density/frontend/public/javascripts/countly.views.js
> CRUD - density, CRUD - browser

- plugins/push/frontend/public/javascripts/countly.models.js
Remove user property type mapper and use enum type same as dto object values.
> fix: Map user property type error

- frontend/express/public/core/device-and-type/javascripts/countly.models.js
- frontend/express/public/core/device-and-type/javascripts/countly.views.js
- frontend/express/public/core/device-and-type/templates/technologyHomeWidget.html
- frontend/express/public/core/geo-countries/javascripts/countly.views.js
- frontend/express/public/core/geo-countries/templates/countriesHomeWidget.html
- frontend/express/public/core/home/javascripts/countly.views.js
- frontend/express/public/core/home/stylesheets/_main.scss
- frontend/express/public/core/home/templates/home.html
- frontend/express/public/core/home/templates/widgetTitle.html
- frontend/express/public/core/session-overview/javascripts/countly.views.js
- frontend/express/public/core/session-overview/templates/sessionsHomeWidget.html
- frontend/express/public/localization/dashboard/dashboard.properties
- plugins/crashes/frontend/public/javascripts/countly.views.js
- plugins/crashes/frontend/public/templates/crashesHomeWidget.html
- plugins/sources/frontend/public/javascripts/countly.views.js
- plugins/sources/frontend/public/templates/searchedTermsHomeWidget.html
- plugins/sources/frontend/public/templates/sourcesHomeWidget.html
- plugins/views/frontend/public/javascripts/countly.views.js
- plugins/views/frontend/public/templates/viewsHomeWidget.html
*views
*sources+keywords
*core
*crashes
> Home widgets fixes:

- api/utils/rights.js
Reverts Countly/countly-server#2902
> Revert "fixes for right to allow fetching collection"

- plugins/push/frontend/public/javascripts/countly.views.component.common.js
- plugins/push/frontend/public/javascripts/countly.views.js
- plugins/push/frontend/public/localization/push.properties
- plugins/push/frontend/public/templates/common-components.html
Fix: media is not displayed when user edits a push notification.
Fix: global push settings locales not found error
> fix: Media url error on edit push notificaiton

- plugins/push/frontend/public/javascripts/countly.models.js
- plugins/push/frontend/public/templates/push-notification-drawer.html
Bonus fix: add only selected locales when creating a push notification message.
> fix/ missing locale select event error

- frontend/express/public/core/user-management/javascripts/countly.views.js
- adding fallback for cases that member doesn't have permission object.
> added permission check before open drawer.

- plugins/star-rating/frontend/public/templates/feedback-popup.html
- reset emoji states after 5 seconds.
- hide popup automatically after 5 seconds.
- open popup with the initial state after closed once.
> [ratings-fixes] reset popup after 5 seconds.

- frontend/express/public/core/app-management/javascripts/countly.views.js
- frontend/express/public/core/app-management/templates/app-management.html
- frontend/express/public/javascripts/countly/vue/components/helpers.js
- frontend/express/public/stylesheets/styles/blocks/_notification-toasts.scss
- plugins/data_migration/frontend/public/javascripts/countly.views.js
- plugins/data_migration/frontend/public/localization/data_migration.properties
1)Added warning if app is redirected.
2)Added redirection removal in pp configuration.
3)Fixed notification styling(based on new UI styling)
> Bugfix. App redirection

- plugins/push/frontend/public/javascripts/countly.models.js
- plugins/push/frontend/public/javascripts/countly.views.component.common.js
Fix global error mapper and display global error at the top of the errors table rows.
> fix: Global error mapper

- plugins/crashes/frontend/public/javascripts/countly.views.js
- plugins/crashes/frontend/public/templates/crashgroup.html
These placeholders are needed to inject content and vuex module from other plugins.
> Add placeholders to crashes plugin

- frontend/express/public/javascripts/countly/vue/templates/datatable.html
> [Bugfix][SER-55] Search field+ enter on top of table caused reload.

- frontend/express/public/core/user-management/javascripts/countly.views.js
- frontend/express/public/core/user-management/stylesheets/_main.scss
- frontend/express/public/core/user-management/templates/data-table.html
- frontend/express/public/core/user-management/templates/user-management.html
- frontend/express/public/localization/dashboard/dashboard.properties
- Update user management table columns
- Update user management filter interface
- Add filter based on user group
> [SER-54] Improve user management

- frontend/express/public/core/user-management/javascripts/countly.views.js
- frontend/express/public/core/user-management/stylesheets/_main.scss
- frontend/express/public/core/user-management/stylesheets/_table.scss
- frontend/express/public/core/user-management/templates/data-table.html
- Clicking reset filter will apply the filter right away
- Remove `no-bg-hover` class from reset filter button
- Set filter dropdown width
> [SER-54] User management filter reset

- frontend/express/public/javascripts/countly/vue/components/input.js
- frontend/express/public/javascripts/countly/vue/templates/selectx.html
- frontend/express/public/stylesheets/styles/blocks/_select.scss
Update the condition for showing search field in select-x component
> [SER-183] [core] Update select-x

- frontend/express/public/core/events/javascripts/countly.overview.views.js
- frontend/express/public/core/events/stylesheets/_main.scss
- frontend/express/public/core/events/templates/overview.html
- Add the missing name to each block
- Bring back the right yAxis, number of ticks and min interval
- Improve borders of blocks
> Monitor events fixes and improvements

- plugins/crashes/frontend/public/javascripts/countly.models.js
Total is the number of users:
https://github.com/Countly/countly-server/blob/master/plugins/crashes/api/api.js#L797
> fix number of occurences on crash details page

- plugins/push/api/api-message.js
- plugins/push/frontend/public/javascripts/countly.models.js
- plugins/push/frontend/public/javascripts/countly.views.js
- plugins/push/frontend/public/localization/push.properties
- plugins/push/frontend/public/templates/push-notification-tab.html
*Table gets reloded after update/delete/create of push
*Correct fallback if name is missing for displaying name in table
*Correct sorting for triggers.start
> fixes for push table.

- frontend/express/public/javascripts/countly/vue/components/vis.js
Color mismatch is fixed between legend and chart line in multi-legends as chart data changes.
> Fix: Chart legends.

- frontend/express/app.js
- frontend/express/public/localization/dashboard/dashboard.properties
This will assign the uploaded image to the correct user in db
> [SER-255] [core] Fix user image update

- api/parts/mgmt/app_users.js
- frontend/express/public/javascripts/countly/countly.app.users.js
- plugins/crashes/api/api.js
- plugins/hooks/api/parts/triggers/internal_event.js
- plugins/push/api/api.js
- plugins/star-rating/api/api.js
- plugins/views/api/api.js
Search results for `i/app_users/delete`
- plugins/hooks/frontend/public/javascripts/countly.views.js:375 -> front-end, no update
- plugins/hooks/frontend/public/localization/hooks_hi.properties:70 -> localization, no update
- plugins/hooks/frontend/public/localization/hooks_sl.properties:70 -> localization, no update
- plugins/hooks/frontend/public/localization/hooks_vi.properties:70 -> localization, no update
- plugins/hooks/frontend/public/localization/hooks_my.properties:70 -> localization, no update
- plugins/hooks/frontend/public/localization/hooks_bs.properties:70 -> localization, no update
- plugins/hooks/frontend/public/localization/hooks_fa.properties:70 -> localization, no update
- plugins/hooks/frontend/public/localization/hooks.properties:72 -> localization, no update
- …
> [SER-129] Ensure consistency when purging app user

- plugins/populator/frontend/app.js
- plugins/populator/frontend/public/stylesheets/demo/banking.css
- plugins/populator/frontend/public/stylesheets/demo/ecommerce.css
- plugins/populator/frontend/public/stylesheets/demo/gaming.css
- plugins/populator/frontend/public/stylesheets/demo/healthcare.css
- plugins/populator/frontend/public/stylesheets/demo/navigation.css
- plugins/populator/frontend/public/templates/demo-banking.html
- plugins/populator/frontend/public/templates/demo-content-2-cols.html
- plugins/populator/frontend/public/templates/demo-content-3-cols.html
- plugins/populator/frontend/public/templates/demo-ecommerce.html
- plugins/populator/frontend/public/templates/demo-gaming.html
- plugins/populator/frontend/public/templates/demo-healthcare.html
- plugins/populator/frontend/public/templates/demo-navigation.html
- plugins/views/frontend/public/stylesheets/heatmap.css
- Fixed checkbox check mark
- Add links to footer items
- Add more content so the page can be scrolled
> [SER-218] Heatmap demo page updates

- frontend/express/public/javascripts/countly/vue/components/input.js
Fixed scrolling issue when switching tabs in Querybuilder.
> [SER-167]: In dropdowns the scroll bar is not shown by default

- Gruntfile.js
- frontend/express/public/javascripts/countly/countly.hotkeys.js
- frontend/express/views/dashboard.html
Just a thought... @ar2rsawseen
> [core] Hotkeys support

- frontend/express/app.js
This checks if an uploaded image is really an image
> [SER-287] [core] Improve user image validation

- frontend/express/public/core/app-management/javascripts/countly.views.js
Fixed update issue with multiple keys of a plugin in app settings.
> [SER-247]: Add 'currency' field for revenue

- Dockerfile-api
- Dockerfile-centos-api
- Dockerfile-centos-frontend
- Dockerfile-frontend
Reverts Countly/countly-server#3578
> Revert "Decrease vulnerabilities on Dockerfiles"

- plugins/logger/install.js
As first pull request was errornous, branch was incorrectly branched, previous PR for SER-359 is closed. I've created this PR
> [SER-359] Convert to cap is done when collection exists

- plugins/slipping-away-users/frontend/public/templates/slipping-away-users.html
hardcoded column widths removed
> [SER-342] Slipping way users table width arranged

- plugins/dashboards/frontend/public/javascripts/countly.widgets.note.js
- plugins/dashboards/frontend/public/stylesheets/main.scss
- plugins/dashboards/frontend/public/templates/widgets/note/widget.html
increases z-index and always showing scrollbar
> [SER-334] Notes wrapping on dashboards

- api/parts/mgmt/users.js
- frontend/express/public/core/notes/javascripts/countly.models.js
- frontend/express/public/javascripts/countly/vue/components/vis.js
- Update graph notes
- Multiple tooltip on graph notes
- Line/bar switching on charts fixed.
> Fixes: Bugs on master

- frontend/express/public/core/events/javascripts/countly.overview.models.js
- frontend/express/public/core/events/javascripts/countly.overview.views.js
Replaces comparision with keys instead of name/groupId
> [SER-280] Format duration properly in Events Overview

- frontend/express/public/core/events/javascripts/countly.details.models.js
fixes issue with yAxisIndex of multiple y axis chart.
> [SER-279] Format duration properly in All Events

- frontend/express/public/javascripts/utils/jsoneditor/codemirror.js
- frontend/express/public/stylesheets/jsoneditor/codemirror.css
Codemirror is updated to version 6.65.7
> [SER-386] update codemirror to latest

- frontend/express/public/javascripts/utils/jquery.xss.js
Updated with the latest version 
https://github.com/leizongmin/js-xss/blob/master/dist/xss.js
> [SER-387] jquery.xss is updated with latest version

- frontend/express/public/javascripts/countly/countly.template.js
- plugins/plugins/frontend/public/javascripts/countly.views.js
Switch Applications and Settings menu item position
> [core] [plugins] Update Applications and Settings menu item position

- api/parts/data/exports.js
- bin/scripts/fix-data/clear_push_duplicates.js
- frontend/express/public/localization/dashboard/dashboard.properties
Adding timeout in export finalizing in case it goes through transform function to do not finalize to soon.
+some small fixes
> Adding timeout in export finalizing in case it goes through transform function to do not finalize to soon.

- api/parts/mgmt/users.js
- frontend/express/public/core/notes/javascripts/countly.models.js
- frontend/express/public/javascripts/countly/vue/components/vis.js
- plugins/dashboards/frontend/public/templates/widgets/analytics/widget.html
- plugins/push/frontend/public/templates/push-notification-tab.html
> [SER-254] Annotation (Add Note) feature for time series graphs

- frontend/express/public/javascripts/countly/vue/components/vis.js
- plugins/push/frontend/public/templates/push-notification-tab.html
Added weekly grouping in custom range selections and some visual improvements.
> [SER-254] Annotation plugin

- api/parts/data/exports.js
> Allow passing format to stream function for dates when exporting

- plugins/crashes/api/api.js
- plugins/crashes/frontend/public/javascripts/countly.models.js
- plugins/crashes/frontend/public/javascripts/countly.views.js
- plugins/crashes/frontend/public/localization/crashes.properties
- plugins/crashes/frontend/public/templates/overview.html
- Remove table row click handler so user will not navigate to other page when trying to click row checkbox
- Make sure that row selection is reset when action is done
- Check failed crash group deletion and show failed crash group deletion with a popup
> [SER-379] Multiple crash deletion fix

- frontend/express/public/javascripts/countly/vue/components/date.js
- frontend/express/public/javascripts/countly/vue/templates/datepicker.html
- frontend/express/public/stylesheets/styles/blocks/_dropdown.scss
CSS's has been changed to be retention/component specific.
> [SER-414] Minor visual issues in the Retention view

- frontend/express/public/core/user-management/stylesheets/_table.scss
- frontend/express/public/core/user-management/templates/data-table.html
Fix for in case of multiple groups
> [SER-404] Make group names in user list clickable

- bin/docker/modify.sh
Fix applied to build ab-testing model for default docker images.
> docker python dependency for ab-testing model

- frontend/express/public/javascripts/countly/countly.common.js
- frontend/express/public/javascripts/countly/countly.helpers.js
- frontend/express/public/javascripts/countly/vue/components/layout.js
- frontend/express/public/javascripts/countly/vue/core.js
Adds a new component to display persistent notification on every page
> Persistent notification

- frontend/express/app.js
- frontend/express/public/core/user-management/stylesheets/_table.scss
- frontend/express/public/core/user-management/templates/user-management.html
- plugins/data-manager/frontend/public/templates/event-groups.html
- plugins/data-manager/frontend/public/templates/events-default.html
- Use cly-main in data manager plugin so notification will show up on data manager pages
- Use cly-main in user management plugin so notification will show up on user management pages
- Do not delete notification from session so it will still show up when page is refreshed
> License notification updates

- frontend/express/public/javascripts/countly/countly.common.js
[feature] added optional parameter to return seconds
> [SER-441] Optional parameter to return seconds while formatting time from seconds timestamp

- frontend/express/public/javascripts/countly/vue/components/vis.js
- frontend/express/public/stylesheets/styles/blocks/_vis.scss
Added minimize tooltip for widgets that has minimum size
> [SER-254] Annotation plugin fixes

- frontend/express/public/javascripts/countly/vue/components/vis.js
- frontend/express/public/javascripts/utils/lodash.mergeWith.js
- frontend/express/views/dashboard.html
- Replaces `merge` with `mergeWith`
- removes duplicate import of simpleUpload
> [SER-440] default-properties-are-not-being-applied-on-dual-axis-charts

- Dockerfile-centos-api
- Dockerfile-centos-frontend
Puppeteer libraries added to fix dependency issue for centos images
> added required libraries for puppeteer

- frontend/express/public/javascripts/countly/vue/components/datatable.js
Added watcher for customFileName prop to check current state.
> [SER-446] Add stringified Drill query to the export file name

- api/utils/common.js
Whitelist of the tags and attributes has been changed. Sanitizing method is changed
- we check if the tag is in whitelist
- loop through matched tags. if attributes of the tag is in whitelist of the tags attributes
> [SER-463] sanitize html hooks

- frontend/express/public/javascripts/countly/vue/components/vis.js
reverts 10887d7f624585817132783d58a8e4528dc0c381
> Fixes chart formatter not accepting multiple args

- plugins/compliance-hub/frontend/public/javascripts/countly.models.js
BUGFIX to make sure only data for this user is exported.
Fixed params structure so they get passed propery on export
> [SER-471]In user profiles consent table export exports ALL users, not only this one

- frontend/express/public/javascripts/countly/countly.common.js
adds shorter formatting for date and time.
> [SER-395]  Custom property marked as Date type is not displayed like date in User Profiles

- plugins/hooks/frontend/public/javascripts/countly.models.js
- plugins/hooks/frontend/public/javascripts/countly.views.js
- plugins/hooks/frontend/public/localization/hooks.properties
- plugins/hooks/frontend/public/templates/vue-table.html
Implemented custom export function for hooks plugin
> [SER-338] Column titles are not user friendly

- api/utils/countly-request/index.js
- api/utils/countly-request/package-lock.json
- api/utils/countly-request/package.json
Oauth support removed from countly request. tidy up
> [SER-443] replace request package with alternative

- plugins/data-manager/frontend/public/javascripts/countly.views.js
[[fix] event transformation radio button
> [SER-438] Invalid values on opening form when editing transformation with regexp in data manager 

- frontend/express/public/javascripts/countly/vue/components/date.js
- frontend/express/public/javascripts/countly/vue/templates/datepicker.html
> [SER-430] Various date filtering and date picker related improvements

- frontend/express/public/core/user-analytics-overview/javascripts/countly.views.js
- frontend/express/public/javascripts/countly/countly.common.js
- frontend/express/public/javascripts/countly/vue/components/date.js
- plugins/crashes/frontend/public/javascripts/countly.widgets.crash.js
- plugins/dashboards/frontend/public/javascripts/countly.widgets.analytics.js
- plugins/dashboards/frontend/public/javascripts/countly.widgets.events.js
Moved period adjustment to getPeriodForAjax function (Was in date picker before. was causing issues in different timezones)
> fixes for cases in dashboard when selected single day in past.

- plugins/data-manager/frontend/public/localization/data-manager.properties
- plugins/data-manager/frontend/public/stylesheets/main.scss
[SER-427]
[SER-427]: https://countly.atlassian.net/browse/SER-427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [data-manager] Allow expiration of custom user properties

- frontend/express/public/javascripts/countly/vue/components/date.js
BugFix: When selecting "inTheLast" option with monthly type in retention plugin, date picker would break on other pages
> [SER-430]  Various date filtering and date picker related improvements

- api/lib/countly.common.js
- api/lib/countly.model.js
- plugins/dashboards/api/parts/dashboards.js
[SER-378]
[SER-378]: https://countly.atlassian.net/browse/SER-378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [dashboards] Fix automatically changing graphs in widgets

- plugins/data-manager/frontend/public/localization/data-manager.properties
> [SER-562] Ability to mask device_id

- api/parts/mgmt/app_users.js
- api/utils/requestProcessor.js
- bin/scripts/add_indexes.js
- plugins/pluginManager.js
[core] Do not fetch masking config if masking is not enabled
[users] [SER-223]App user export is now not using filesystem anymore(So it will work on docker) Changed output format!! After upgrade must run ./bin/scripts/add_indexes.js to ensure index on exports collection.
[SER-223]: https://countly.atlassian.net/browse/SER-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SER-223][core][users]App user export to database(not using filesystem anymore) + small fix for masking.

- frontend/express/public/core/events/javascripts/countly.details.models.js
- frontend/express/public/core/events/javascripts/countly.overview.models.js
- frontend/express/public/javascripts/countly/vue/components/helpers.js
- plugins/data-manager/frontend/public/javascripts/countly.views.js
- plugins/data-manager/frontend/public/templates/event-detail.html
- plugins/data-manager/frontend/public/templates/event-group-detail.html
- plugins/data-manager/frontend/public/templates/event-groups.html
- plugins/data-manager/frontend/public/templates/events-default.html
- [Fix] keys with HTML Entities no longer escape.
> [SER-531] display-bug-in-the-all-events-view-for-events-with-ampersand-in-its-name-enterprise-v-22-09

- api/utils/localization.js
- frontend/express/app.js
- plugins/data_migration/api/data_migration_helper.js
- plugins/errorlogs/api/api.js
And this change also includes **[SER-556]** Read theme needs file name sanitization.
[SER-556]: https://countly.atlassian.net/browse/SER-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SER-552] Server side localization needs sanitization of file names

- plugins/views/frontend/public/javascripts/countly.models.js
- plugins/views/frontend/public/javascripts/countly.views.js
> SER-349: View duration metric and its formatting

- bin/docker/k8s/countly-ingress-baremetal_setup.yaml
Ingress file for baremetal and unmanaged k8 setup
> Ingress file for baremetal/unmanaged k8 setup

- plugins/pluginManager.js
Needed functions to auto enable/disable global masking setting on enabling/disabling masking.
> [data-manager] Additions to data masking.

- plugins/data-manager/frontend/public/javascripts/countly.views.js
[fix] remove unnecessary escaping
> [SER-582] Data Manager ---> Event Names are mismatching in Transformations

- frontend/express/public/javascripts/countly/vue/components/date.js
- frontend/express/public/javascripts/countly/vue/templates/datepicker.html
Reverts Countly/countly-server#4068
> Revert "[SER-603] allow disabling range modes in date picker (custom period)"

- plugins/dbviewer/frontend/public/javascripts/countly.models.js
- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- plugins/dbviewer/frontend/public/templates/aggregate.html
Fixed bug handling in aggregation queries.
> [SER-600] Add query linking to dbviewer

- api/parts/mgmt/apps.js
- test/2.api/05.update.user.js
When an app is deleted, that app id should be removed from user and group permission
> [SER-632] Update user and group permission when an app is deleted

- plugins/data-manager/frontend/public/javascripts/countly.views.js
- plugins/data-manager/frontend/public/templates/event-group-drawer.html
[fix] no save toast until data is actaually edited.
> [SER-581] Data Manager ---> Changing the visibility of an unplanned event

- frontend/express/public/core/events/javascripts/countly.details.models.js
- frontend/express/public/core/events/javascripts/countly.details.views.js
- frontend/express/public/core/events/templates/eventsTable.html
- [fix] sorting issue caused due to numbers being passed as strings in event details page.
> [SER-641] Fix sorting of integer segmentation in events table

- frontend/express/public/javascripts/countly/vue/components/dropdown.js
- frontend/express/public/javascripts/countly/vue/components/helpers.js
- frontend/express/public/javascripts/countly/vue/components/input.js
- plugins/push/api/api-drill.js
- plugins/push/frontend/public/localization/push.properties
> [push] Drill filter for push action event

- api/parts/mgmt/apps.js
- frontend/express/public/core/user-management/javascripts/countly.views.js
- test/2.api/09.update.app.js
These are updates related to member permission issues
1. Reset permission properly in user edit drawer
2. Update app details response to check permission object when listing app admins and users
> [SER-692] User permission updates

- frontend/express/public/core/user-management/javascripts/countly.views.js
- frontend/express/public/core/user-management/templates/data-table.html
- frontend/express/public/localization/dashboard/dashboard.properties
- [fix] sorting for Role & Group in User Management
- [fix] Blank groups values due to `groupsModel` not initialized
Issue:
Fix:
> [SER-698] Sorting Issue & Blank groups values in User Management

- plugins/data-manager/frontend/public/localization/data-manager.properties
`data-manager.edit-property = Edit Property ` localisation added
> [SER-563] Add an "Edit User Property" button to Data Manager

- plugins/crashes/frontend/public/javascripts/countly.views.js
- plugins/crashes/frontend/public/templates/crashgroup.html
Add notification to show that symbolication is successful/failed
> [SER-514] [crashes] Display symbolication failed/success notification

- frontend/express/public/core/user-management/javascripts/countly.views.js
- frontend/express/public/core/user-management/stylesheets/_drawer.scss
- frontend/express/public/core/user-management/templates/drawer.html
- frontend/express/public/localization/dashboard/dashboard.properties
- [feature] Search bar for features in User Management
> [SER-517] Search functionality for features in CRUD (User Management)

- plugins/two-factor-auth/frontend/app.js
when OTP failed it was not written to failed logins before. Because of that brute force prevention middleware was not functioning even middleware is executed.
> [SER-553] 2fa has no rate limit for guessing token

- frontend/express/public/core/user-management/javascripts/countly.views.js
- frontend/express/public/core/user-management/templates/drawer.html
Old Behaviour:
Everything gets toggled at once,even when search filter is applied.
New Behaviour:
Only search filtered results get toggled.
> [SER-517] Toggle checkbox of only filtered results in User Management

- plugins/push/frontend/public/javascripts/countly.models.js
- plugins/push/frontend/public/javascripts/countly.views.component.common.js
- plugins/push/frontend/public/javascripts/countly.views.js
- plugins/push/frontend/public/stylesheets/main.scss
- plugins/push/frontend/public/templates/common-components.html
- plugins/push/frontend/public/templates/push-notification-drawer.html
- plugins/push/frontend/public/templates/push-notification-tab.html
some UI fixes
and segmentation selection while editing in draft state
> [SER-741] Adding the right-click feature to [push] campaign names

- package-lock.json
- package.json
Reverts Countly/countly-server#4319
> Revert "Bump sass from 1.63.3 to 1.63.6"

- plugins/populator/frontend/public/javascripts/countly.models.js
+ and improved error message details in the user interface
> Fix: URL length issue in data populator plugin's edit request

- bin/upgrade/DEV/scripts/remove_deleted_recors_from_widgets.js
> [SER-688] Delete dashboard widgets if a related Funnel is deleted

- frontend/express/public/javascripts/countly/vue/templates/sidebar/analytics-menu.html
- frontend/express/public/javascripts/countly/vue/templates/sidebar/language-menu.html
- frontend/express/public/javascripts/countly/vue/templates/sidebar/sidebar.html
- frontend/express/public/javascripts/countly/vue/templates/sidebar/users-menu.html
- frontend/express/views/dashboard.html
https://countly.atlassian.net/browse/SER-781
> [SER-781] Added data-test-id attrs to sidebar elements

- frontend/express/libs/members.js
- frontend/express/public/core/app-management/javascripts/countly.views.js
- frontend/express/public/javascripts/countly/countly.template.js
- plugins/pluginManager.js
1. No license in enterprise, then
- dashboard not usable
2. On first enterprise install/upgrade
- After app creation, we redirect to license manager
- Dashboard not usable
> [SER-733] License Manager behavior when license does not exist

- frontend/express/libs/members.js
emtyPermission object was wrongly constructed causing frontend crash
> [SER-771] emtyPermission object was wrongly constructed

- plugins/crashes/frontend/public/javascripts/countly.views.js
Filtering app version is broken, most likely because of https://github.com/Countly/countly-enterprise-plugins/commit/a37a6bfadc76397e6bbf66bb2bf26ccfab998bcb#diff-d0124da27810bf265a63817e9adf412b0c225c7b4f53b2d6dab68b02df701c59R102
> [crashes] Fix query builder property types

- api/utils/common.js
> [bugfix] Dbviewer ignores filter on export if any value is null in filter

- plugins/views/api/api.js
> [core] Improvements for views to correctly count unique user count for one view if multiple views with same name sent in single request.

- plugins/views/api/api.js
[views] Fix for unique value recording for segments.
> [views] Store segmentation in viewdata to correctly record uvc, bounces exits(session post items) for different segments in aggregated data.

- api/parts/mgmt/cms.js
- frontend/express/public/javascripts/countly/vue/components/layout.js
- frontend/express/public/javascripts/countly/vue/components/sidebar.js
- plugins/guides/frontend/public/stylesheets/main.scss
- Hide/show guide based on flag in CMS
- fixed walkthrough dialog size
> [SER-740] [guides] small changes

- api/parts/data/exports.js
- api/utils/requestProcessor.js
Added support for DrillDB query in RequestQuery Export
Added support for custom transformation of object in export.stream
> [SER-721] Add survey export to report manager

- frontend/express/public/localization/dashboard/dashboard.properties
Under /countly-server/frontend/express/public/localization/dashboard/dashboard.properties
> [SER-801] Debug-options text added

- api/parts/mgmt/cms.js
- frontend/express/public/javascripts/countly/countly.cms.js
- frontend/express/public/javascripts/countly/vue/components/layout.js
- frontend/express/public/javascripts/countly/vue/components/sidebar.js
- plugins/guides/api/api.js
- plugins/guides/frontend/public/javascripts/countly.models.js
- plugins/guides/frontend/public/javascripts/countly.views.js
- plugins/guides/frontend/public/stylesheets/main.scss
- plugins/guides/frontend/public/templates/dialog.html
- plugins/guides/frontend/public/templates/overview-component.html
- plugins/guides/frontend/public/templates/walkthrough-component.html
- plugins/guides/frontend/public/templates/walkthroughs-component.html
- UI changes to thumbnails
- Refresh interval is 2 hours for CMS cache
- Force refresh CMS flag
- Check config flag if CMS flag is false
- Feedback widget uses domain as device_id
> [SER-740] [guides] updates

- api/utils/common.js
- frontend/express/app.js
- frontend/express/libs/members.js
Check license at render instead of only login.
> [License] Check license at render 

- frontend/express/app.js
[SER-826]
[SER-826]: https://countly.atlassian.net/browse/SER-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [core] Do not set session cookie on widget load

- ui-tests/cypress/e2e/feedback/ratings/widgets.cy.js
- ui-tests/cypress/fixtures/generated/widgetsRates/widgetRate.json
- ui-tests/cypress/fixtures/generators/generateFixtures.js
- ui-tests/cypress/fixtures/generators/widgets/index.js
- ui-tests/cypress/fixtures/generators/widgetsRates/index.js
- ui-tests/cypress/lib/feedback/ratings/demoWidgetPage.js
- ui-tests/cypress/lib/feedback/ratings/widgets.js
- ui-tests/cypress/support/commands.js
- ui-tests/cypress/support/elements/feedback/ratings/widgets.js
- ui-tests/cypress/support/helper.js
- ui-tests/package-lock.json
- ui-tests/package.json
https://countly.atlassian.net/browse/QT-44
> [QT-44] Added verify widget details comment and ratings tab data case

- ui-tests/cypress/support/helper.js
https://countly.atlassian.net/browse/QT-46
> [QT-46] Fix day of date from 0X to X format

- plugins/views/api/api.js
- plugins/views/scripts/omitViewSegments.js
- plugins/views/tests.js
Added script for omitting segment
Updated backed to have an endpoint for omitting segments and also use saved omitting structure to do not record omitted segments on incoming data.
> [core][views] Omitting views segments  [SER-929] [SER-931]

- frontend/express/public/core/app-management/javascripts/countly.views.js
- frontend/express/public/core/app-management/templates/app-management.html
- frontend/express/public/localization/dashboard/dashboard.properties
Added App Domain field in App Management Section
> [SER-743] [SER-913] Add App Domain in App Management 

- frontend/express/public/core/onboarding/templates/app.html
- frontend/express/public/core/onboarding/templates/consent.html
- frontend/express/public/javascripts/countly/vue/components/form.js
- frontend/express/views/setup.html
https://countly.atlassian.net/browse/QT-47
> [QT-47]v2 Add data-test-id attributes into onboarding page elements 

- plugins/data_migration/api/data_migration_helper.js
Fix misspelling 'lenght' --> 'length'
> Fix misspelling in data migration plugin

- frontend/express/public/core/onboarding/javascripts/countly.views.js
Some checks to make onboarding work in offline mode
> [onboarding] Onboarding offline

- frontend/express/public/core/device-and-type/templates/technologyHomeWidget.html
- frontend/express/public/core/events/templates/eventsHomeWidget.html
- frontend/express/public/core/geo-countries/templates/countriesHomeWidget.html
- frontend/express/public/core/home/templates/home.html
- frontend/express/public/core/home/templates/widgetTitle.html
- frontend/express/public/core/session-overview/templates/sessionsHomeWidget.html
- frontend/express/public/javascripts/countly/vue/components/helpers.js
- frontend/express/public/javascripts/countly/vue/components/input.js
- frontend/express/public/javascripts/countly/vue/components/progress.js
- frontend/express/public/javascripts/countly/vue/components/vis.js
- plugins/crashes/frontend/public/templates/crashesHomeWidget.html
- plugins/sources/frontend/public/templates/sourcesHomeWidget.html
- ui-tests/cypress/support/elements/feedback/ratings/widgets.js
https://countly.atlassian.net/browse/QT-56
> [QT-56] Add Data-test-id attributes into Home page elements

- api/parts/mgmt/app_users.js
+[bugfix] Filter was not working on isset/ is not set
> [SER-1033] Optimize loyalty calculation

- plugins/push/api/api-message.js
Updating app settings were breaking push message creation
> [SER-1062] Push: updated credentials query for message creation

- .github/workflows/release_notice.yml
Changelog link for discord workflow will be updated based on the repo being use to perform release.
> soft coding the changelog link

- bin/commands/scripts/user_mgmt.js
Current behaviour:
New behaviour:
> fix: remove_user command for informative output

- plugins/push/api/jobs/schedule.js
- plugins/push/api/jobs/util/connector.js
- plugins/push/api/jobs/util/resultor.js
- plugins/push/api/jobs/util/stream_wrapper.js
- plugins/push/api/send/data/message.js
- plugins/push/api/send/sender.js
also added a filter to prevent consuming pushes of messages that job hasn't finished yet
> [push] update message state properly while populating push queue

- package-lock.json
- package.json
Reverts Countly/countly-server#4678
> Revert "Bump async from 3.2.4 to 3.2.5"

- package-lock.json
- package.json
Reverts Countly/countly-server#4918
> Revert "Revert "Bump async from 3.2.4 to 3.2.5""

- bin/scripts/performance-monitoring/apm_events_delete.js
Script to remove apm events per app from `drill_events` and `apm` collection.
> [SER-1127] Script to remove apm events per app

- frontend/express/public/javascripts/countly/vue/components/helpers.js
- ui-tests/cypress/lib/home/home.js
- ui-tests/cypress/support/components/quickstartPopover.js
Added data-test-id into back button
> Added data-test-id into back button

- plugins/data-manager/frontend/public/localization/data-manager.properties
> [SER-875] Transformation to copy event segmentation to user custom properties

- plugins/dbviewer/frontend/public/javascripts/countly.views.js
- plugins/dbviewer/frontend/public/templates/tab.html
forceLoading prop was non-existent and giving an error, removed and observed no error. 
Let me know if I should bring it back.
Grouped together some v-if checks
> [SER-1166] add sorting and filtering to projection field in dbviewer

- frontend/express/public/javascripts/countly/vue/components/dialog.js
- plugins/populator/frontend/public/javascripts/countly.models.js
- plugins/populator/frontend/public/javascripts/countly.views.js
- plugins/populator/frontend/public/localization/populator.properties
- plugins/populator/frontend/public/templates/populator.html
> [new-data-populator] BugFix: Calculating spike possibility in data populator

- bin/upgrade/DEV/scripts/migrate_alerts_data.js
pluginManager's path in migration script(for alerts) was wrong. Path is updated
> pluginManager path update (hotfix)

- ui-tests/cypress/lib/dashboard/home/home.js
https://countly.atlassian.net/browse/SER-1182
https://github.com/Countly/countly-enterprise-plugins/pull/1042
> Updated userdata.total-user-tooltip text

- ui-tests/cypress/lib/dashboard/home/home.js
https://countly.atlassian.net/browse/SER-1182
> Updated userdata.total-user-tooltip text for web app

- plugins/push/api/send/platforms/i.js
topics were not being extracted correctly when there was a non letter character at the beginning
> [SER-1497] p12 file not being parsed correctly

- ui-tests/cypress/api/addData.js
- ui-tests/cypress/api/createToken.js
- ui-tests/cypress/api/feedbackWidgetsCreate.js
- ui-tests/cypress/e2e/dashboard/feedback/ratings/widgets.cy.js
- ui-tests/cypress/e2e/dashboard/manage/alerts/alerts.cy.js
- ui-tests/cypress/fixtures/generated/alerts/alert.json
- ui-tests/cypress/fixtures/generators/alerts/index.js
- ui-tests/cypress/fixtures/generators/generateFixtures.js
- ui-tests/cypress/lib/dashboard/feedback/ratings/widgets.js
- ui-tests/cypress/lib/dashboard/manage/alerts/alerts.js
- ui-tests/cypress/support/commands.js
- ui-tests/cypress/support/constants.js
- ui-tests/cypress/support/elements/dashboard/manage/alerts/alerts.js
- ui-tests/cypress/support/helper.js
Includes
https://countly.atlassian.net/browse/QT-180
https://countly.atlassian.net/browse/QT-181
https://countly.atlassian.net/browse/QT-182
https://countly.atlassian.net/browse/QT-183
https://countly.atlassian.net/browse/QT-184
https://countly.atlassian.net/browse/QT-185
https://countly.atlassian.net/browse/QT-187
https://countly.atlassian.net/browse/QT-188
https://countly.atlassian.net/browse/QT-189
https://countly.atlassian.net/browse/QT-190
> [QT-180] Added create alert test cases

- ui-tests/cypress.config.sample.js
https://countly.atlassian.net/browse/QT-192
> [QT-192] Update config delete video and ps fails if the spec is skipped

- frontend/express/public/javascripts/countly/vue/components/dropdown.js
- frontend/express/public/javascripts/countly/vue/templates/selectx.html
- plugins/alerts/frontend/public/templates/vue-main.html
- ui-tests/cypress/e2e/dashboard/manage/alerts/alerts.cy.js
- ui-tests/cypress/lib/dashboard/manage/alerts/alerts.js
- ui-tests/cypress/support/commands.js
- ui-tests/cypress/support/elements/dashboard/manage/alerts/alerts.js
https://countly.atlassian.net/browse/QT-191
> [QT-191] Added update cases to alerts

- ui-tests/cypress/e2e/dashboard/manage/alerts/alerts.cy.js
- ui-tests/cypress/lib/dashboard/manage/alerts/alerts.js
- ui-tests/cypress/support/elements/dashboard/manage/alerts/alerts.js
https://countly.atlassian.net/browse/QT-193
> [QT-193] Delete Alert 

- ui-tests/cypress/lib/dashboard/feedback/ratings/widgets.js
https://countly.atlassian.net/browse/SER-1520
> [SER-1520]v3 using 'let' instead of 'var' in test loop indexes 

- ui-tests/cypress/e2e/dashboard/analytics/loyalty/userActivity.cy.js
https://countly.atlassian.net/browse/QT-195
> [QT-195] Fix e2e user analytics define path

- ui-tests/cypress/lib/dashboard/feedback/ratings/widgets.js
https://countly.atlassian.net/browse/SER-1521
> [SER-1521] Removed  break code  from navigateToWidgetsDetailPage method 

- bin/commands/countly.sh
- bin/countly.install_rhel.sh
- bin/countly.install_ubuntu.sh
fixed argon2 node module installation issue and rectified the grep command for capturing the value of offline_mode.
> fixed countly installation and argon2 module issue

- frontend/express/public/stylesheets/vue/clyvue.scss
> fix nps/survey background color

- plugins/alerts/frontend/public/javascripts/countly.views.js
the bug which is occured when updating the alerts trigger part is fixed
> [SER-1573] old data remains when the alerts metric is updated

- plugins/alerts/frontend/public/templates/vue-main.html
- ui-tests/cypress/e2e/dashboard/manage/alerts/alerts.cy.js
- ui-tests/cypress/lib/dashboard/manage/alerts/alerts.js
https://countly.atlassian.net/browse/QT-198
> [QT-198]  Alert trigger component changing fixed on automation

- plugins/push/api/send/sender.js
hotfix: filtering by _id while loading push config
> [SER-1598] Push config is not being loaded properly

- ui-tests/cypress/lib/dashboard/analytics/views/views.js
https://countly.atlassian.net/browse/SER-1613
> Removed br tags from text

- frontend/express/public/javascripts/countly/vue/templates/sidebar/users-menu.html
- ui-tests/cypress/e2e/onboarding/onboarding.cy.js
- ui-tests/cypress/support/elements/sidebar/sidebar.js
- ui-tests/cypress/support/navigations.js
https://countly.atlassian.net/browse/QT-223
> [QT-223] log out than log in with created user after onboarding 

- frontend/express/public/core/platform/templates/version_table.html
https://countly.atlassian.net/browse/SER-1754
> [SER-1754] Update version_table header label text

- plugins/views/frontend/public/templates/views.html
> Fixed template tag error

- plugins/push/frontend/public/localization/push.properties
Added more info regarding Timeout settings (in milliseconds)
> SER-1409: Clarify if the time delay is seconds or ms

- ui-tests/cypress/lib/dashboard/analytics/loyalty/timesOfDay.js
- ui-tests/package-lock.json
- ui-tests/package.json
https://countly.atlassian.net/browse/QT-226
> [QT-226] Update cypress version to 13.4.2

- plugins/alerts/api/alertModules/crashes.js
- plugins/alerts/api/parts/common-lib.js
- plugins/alerts/frontend/public/templates/email.html
optimizations with readbatcher
multiple crash alerts can be triggered by /crashes/new
alert e-mails includes a crash link
minor bug and type fixes
> [alerts] improvements in crashes

- frontend/express/public/core/events/templates/overview.html
Fixed duplicate attribute: data-test-id console error
> Fixed duplicate attribute console error

- api/parts/data/cache.js
This reverts commit 92db21f0dd34259decd187239cb3c165c428e34c.
> Revert "[cache] Removing noCursorTimeout from cache cursor"

- frontend/express/public/core/user-activity/javascripts/countly.views.js
- plugins/density/frontend/public/templates/density.html
- plugins/slipping-away-users/frontend/public/javascripts/countly.views.js
Density not appearing
[Make sure we are lot trying to load references to drill if drill is not there (user-activity)
> [SER-1791]  UI fixes density/user-activity

- ui-tests/cypress/e2e/dashboard/feedback/ratings/widgets.cy.js
- ui-tests/cypress/lib/dashboard/feedback/ratings/demoWidgetPage.js
https://countly.atlassian.net/browse/QT-234
> Fix Widget demo page click Agree checkbox fail

- .eslintrc.json
- package.json
Content + journey specific lint config
> Upgrade to es2023 for backend and tests

- ui-tests/package-lock.json
- ui-tests/package.json
https://countly.atlassian.net/browse/QT-261
> [QT-261] Downgrade cypress version to 13.6.4 because of the memory crash

- api/utils/common.js
- plugins/views/tests.js
> [core]Fixes for getting current "day of year" on recording. [views] Fixes for tests

- plugins/pluginManager.js
- plugins/star-rating/frontend/public/javascripts/countly.models.js
Wraps return value inside `value object`
> MongoDb findOneAndDelete Return Value 

- frontend/express/public/javascripts/countly/vue/templates/content/content-header.html
https://countly.atlassian.net/browse/QT-264
> [QT-264] Add data test id to content htmls in countly-server

- ui-tests/cypress/lib/dashboard/feedback/ratings/widgets.js
> Updated add consent label text in automation

- CHANGELOG.md
- plugins/locale/frontend/public/javascripts/countly.models.js
Problem: It was calculating based on the total session count
> Fix: [languages] Calculated total users percentage correctly

- CHANGELOG.md
https://github.com/Countly/countly-enterprise-plugins/pull/1737
> chore: changelog entry

- ui-tests/cypress/lib/dashboard/manage/configurations/configurations.js
> Settings security additional headers text updated

- ui-tests/cypress/lib/dashboard/feedback/ratings/widgets.js
- ui-tests/package.json
(cherry picked from commit fe4955a1c94f605ffe4e78d78f4db36a3718aff9)
> Updated add consent label text

- bin/scripts/expire-data/delete_custom_events.js
…meta
return distinct events from drill_meta 
purpose: deleting faulty/dead events from Data Manager
> Update delete_custom_events.js to  return distinct events from drill_meta

- plugins/star-rating/frontend/public/templates/star-consent-link.html
While creating rating, There is a character limit exceeded issue in the Add user consent text input box.
> [SER-2236] Character limit exceeded issue in feedback widget

- frontend/express/public/javascripts/countly/vue/components/helpers.js
- plugins/sdk/frontend/public/javascripts/countly.views.js
- plugins/sdk/frontend/public/stylesheets/main.scss
- plugins/sdk/frontend/public/templates/config.html
Modified the tooltip we already have but we can instead use a custom one for ourselves (which I did initially and removed at the end)
> [sdk ] Tooltip SDK support information

- frontend/express/public/javascripts/countly/vue/components/helpers.js
- plugins/sdk/frontend/public/javascripts/countly.views.js
- plugins/sdk/frontend/public/stylesheets/main.scss
- plugins/sdk/frontend/public/templates/config.html
Reverts Countly/countly-server#6055
> Revert "[sdk ] Tooltip SDK support information"

- frontend/express/public/javascripts/countly/vue/templates/content/content-header.html
https://countly.atlassian.net/browse/QT-264
> [QT-264] Added data test ids in content header

- CHANGELOG.md
- plugins/push/api/send/data/pers.js
- plugins/push/frontend/public/stylesheets/main.scss
This pull request fixes the following issues:
- [Placeholders in API Push Notifications](https://countly.zendesk.com/agent/tickets/4194)
> [Fix] Placeholders in API push notifications

- frontend/express/public/javascripts/countly/vue/components/content.js
- frontend/express/public/javascripts/countly/vue/templates/UI/option-swapper.html
- frontend/express/public/javascripts/countly/vue/templates/content/UI/content-sidebar-input.html
https://countly.atlassian.net/browse/QT-278
> [QT-278] Added data test ids to content drawer elements

- plugins/remote-config/frontend/public/templates/parameters-drawer.html
- plugins/remote-config/frontend/public/templates/parameters.html
https://countly.atlassian.net/browse/QT-281
> [QT-281] Added data-test-id in parameter-drawer and parameter html files

- CHANGELOG.md
- frontend/express/public/javascripts/countly/vue/components/drawer.js
- frontend/express/public/javascripts/countly/vue/templates/drawer.html
- frontend/express/public/stylesheets/vue/clyvue.scss
This PR contains the fix for [SER-1405] and some HTML refactor.
The refactor was necessary because I had to perform the change to fix the issue in two places that I later noticed were repeated and contained code that would never be valid. Since it was a simple clean-up and the bug was from an internal report, I decided on the refactor.
[SER-1405]: https://countly.atlassian.net/browse/SER-1405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SER-1405] Design drawer component vertical alignment is not correct

- ui-tests/cypress/lib/dashboard/feedback/ratings/demoWidgetPage.js
> Added trim to get widgetId in automation

- .eslintrc.json
- .husky/pre-commit
- package.json
…ngle quotes and remove vue3 subapp specific rules
> new eslint changes and proposal

- CHANGELOG.md
- frontend/express/public/javascripts/countly/vue/components/helpers.js
- frontend/express/public/stylesheets/vue/clyvue.scss
- plugins/star-rating/frontend/public/javascripts/countly.views.js
- plugins/star-rating/frontend/public/stylesheets/widget-detail.scss
- plugins/star-rating/frontend/public/templates/widget-detail.html
This PR also fixes this [issue](https://countly.atlassian.net/browse/SER-1976)
> [SER-1975] There is an status instant error for status tag in NPS, Surveys and  Ratings

- plugins/star-rating/api/api.js
Trimming the input is already possible with the 'Trim trailing and ending spaces' setting. So no need to do more trimming.
> Revert "[star-rating] Trim app version"

- ui-tests/cypress/lib/dashboard/manage/configurations/configurations.js
- ui-tests/cypress/support/commands.js
https://countly.atlassian.net/browse/QT-323
> [QT-323-v2] Fix the scroll issue for Settings

- CHANGELOG.md
Added a performance improvement note and UI bugfixes for journeys.
> Update CHANGELOG with journey performance improvements

- plugins/remote-config/frontend/public/templates/conditions-drawer.html
- plugins/remote-config/frontend/public/templates/conditions.html
- plugins/remote-config/frontend/public/templates/parameters-drawer.html
https://countly.atlassian.net/browse/QT-332
> [QT-332] Added data-test-id for conditions-drawer, conditions and parameters-drawer html files

- plugins/views/scripts/omitViewSegments.js
the current path throws error. found the script under /scripts.
meghana.mr@dev-meghana:/opt/countly/plugins/views$ sudo node omitViewSeg.js node:internal/modules/cjs/loader:1143
throw err;
^
Error: Cannot find module './../../../plugins/pluginManager.js' Require stack:
- /opt/countly/plugins/views/omitViewSeg.js at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15) at Module._load (node:internal/modules/cjs/loader:981:27) at Module.require (node:internal/modules/cjs/loader:1231:19) at require (node:internal/modules/helpers:177:18) at Object.<anonymous> (/opt/countly/plugins/views/omitViewSeg.js:12:21) at Module._compile (node:internal/modules/cjs/loader:1364:14) at Module._extensions..js (node:internal/modules/cjs/loader:1422:10) at Module.load …
> Update script path comment in omitViewSegments.js

- CHANGELOG.md
This changelog update relates to this #6737
> CHANGELOG Update for app creation bug fix

- plugins/remote-config/frontend/public/templates/conditions.html
https://countly.atlassian.net/browse/QT-341
> [QT-341] Added data-test-id for condition data table more, edit and delete butttons

- CHANGELOG.md
Updated version number and fixed entries for users and cohorts.
> Update CHANGELOG for version 24.05.41
