Countly/countly-server

bin/scripts/countly.install.plugins.sh

Seems that Fedora nodesource rpm has no "nodejs>node" symlink

Does not work in Fedora 22

---

api/lib/countly.device.detail.js
frontend/express/public/javascripts/countly/countly.template.js

The returned timestamps of dates will now be corrected for the current time zone so that it is returned in UTC

Small fix to unix timestamp from calendar

---

api/utils/common.js

The default returnOutput will response to client side.
Now add support to resoonse to a callbackfunction when a plugin api call  countly core functions.

[common] common.returnOutput add apiCallback support

---

api/parts/data/fetch.js

The former version omits the JSON parse exceptions. Since the type of "params.qstring.events" still a string after the parse attempt, the if block doesn't get executed, and the function exits silently. Naturally, the system doesn't generate a response for requests that contain bad "events" querystring, and leads to a timeout. Also even the input is parsed without any problems, the parsed input still can be a string, this fix also handles that case.

Fix for fetch.js fetchEvents function

---

README.md

As discussed with @ar2rsawseen by email.
Hall-of-fame is a widget that helps you recognize new/trending/top contributors in your repo. It is designed to be very visual, and change frequently. It autoupdates every hour and requires no maintenance.
Note that by accepting this PR, you will make me a contributor, which means my face will be featured as ’new’ on your Hall-of-fame for one week.
Also note that the widget uses @ar2rsawseen GitHub account to update stats, and makes 10-15 requests to GitHub API per hour (GitHub rate limit is 5,000 per hour).

Added hall-of-fame to README

---

api/utils/common.js

- added optional parameter "returnErrors" to common.validateArgs() method.
- if returnErrors parameter passed as true, validateArgs method returns object with this format.
```
{
result:true,
errors: [],
obj: {field1:value1, field2:value2}
}
```
or
```
{
result:false,
errors: ['Invalid type for arg2'],
obj: {}
}
```
Old usage for `validateArgs` method
```javascript
if (!(args = common.validateArgs(params.qstring.args, argProps))) {
log.d('Not enough params to create message: %j', params.qstring.args);
common.returnMessage(params, 400, 'Not enough args');
return;
}
```
Error response for old method:
```
{
result: "Not enough args"
}
```
New usage
```javascript
var validation = common.validateArgs(params.qstring.args, argProps, true);
if (!(args = validation.obj)) {
log.d('Not enough params …
```

[api] common.validateArgs method improvements.

---

plugins/dbviewer/api/api.js

- SERVER-1097
- now db viewer api accepts parameter below for aggregation support
-- aggregate=1 // required
-- match={"key":"val"}
-- group={"_id":"$platform", "average_rating": {"$avg": "$rating"}}

[aggregate-support] aggregate support added to dbviewer api.

---

frontend/express/public/javascripts/countly/countly.task.manager.js
frontend/express/public/javascripts/countly/countly.views.js
frontend/express/public/stylesheets/main.css
frontend/express/views/dashboard.html

- Reports are now sorted by their start time with the newest at the top.
- Set a maximum width for the data column and its contents in the report manager so it doesn't squeeze the other columns into an unreadable size.
- Removed the date picker from the report manager, it lists all reports at once now.

Report Manager UI tweaks

---

frontend/express/public/stylesheets/main.css

Replaced `max-width` with `width` in the `.report-manager-data-col` parts of the CSS.
> CSS 2.1 leaves the behavior of max-width with table undefined. Firefox supports applying max-width to table elements.

[frontend] used width instead of max-width to resize the data column

---

.editorconfig

I propose we add an editorconfig file to help contributors by allowing them to start hacking around right away without adjusting their editor settings according to the project whitespace conventions :)
For more info, see: https://editorconfig.org

added a project editorconfig file

---

frontend/express/public/javascripts/countly/countly.location.js

I ran into this while developing another plugin. I *think* it's caused by `google.visualization` being already initialized but I'm not sure. Either way, this fixes it by making sure there is a `_chart` to `.draw` before it calls `reDraw`.

[frontend] fixed countlyLocation not drawing a map when geochart is already initialized

---

frontend/express/views/dashboard.html

This fixes apostrophes turning into `&#39;` in event descriptions. See: https://stackoverflow.com/questions/23656516/handlebars-escape-string

[frontend] fixed event description html escaping

---

plugins/plugins/api/api.js
plugins/plugins/frontend/public/javascripts/countly.views.js
plugins/plugins/frontend/public/localization/plugins.properties

- added async plugins check mechanism to plugins plugin.

[async-plugins-check] server-1248

---

bin/countly.install_rhel.sh

Add --ignore-installed flag to installation of supervisor to prevent meld3 conflict.

Add --ignore-installed flag to installation of supervisor

---

bin/commands/scripts/docs.sh
frontend/express/app.js
frontend/express/libs/members.js
test/2.api/14.authorize.token.js

[SERVER-1247] Create a common members utility
Functions moved to members.js. Changes in docs.sh to generate documentation.
[SERVER-1336] also fixed.

 [SERVER-1247] Create a common members utility 

---

bin/scripts/install.nghttp2.sh

https://openssl.org is redirecting to https://www.openssl.org and `wget` can't handle this redirection and can't install openssl-1.0.2h.

Add www to prevent wget error because of domain redirection

---

bin/countly.install.sh
bin/scripts/make.swap.sh

When MongoDB is placed on different instances, there is no hard limitation that would prevent instances with less than 2GB of memory to be used. Script that creates a swap file has been modified to work on smaller VMs (blocksize was reduced so it does not need 1GB of free memory just to create a swap file) and added a check to see if swap space already exists.
Result: using environment variable COUNTLY_OVERWRITE_MEM_REQUIREMENT, you can bypass the warning that 2GB of memory is required and still install countly (it will create a swap file if it does not already exist).
Countly can run on a 1GB node with local MongoDB or even on a 512MB instance if: 
1. MongoDB runs on a different instance
2. A max of 1 api worker by adding "workers: 1" in api/config.js

Allow low memory instances < 2GB with swap

---

extend/.gitignore
extend/aws_ses.example.js

Example of emailing via AWS SES.
Maybe a good idea is to mention it in the documentation under https://resources.count.ly/docs/installing-countly-server#section-using-a-3rd-party-email-server as a separate section called "using a 3rd party email SERVICE"

AWS SES - Simple Email Service example

---

frontend/express/public/javascripts/dom/slimScroll.min.js

Preventing error: "Unable to preventDefault inside passive event listener due to target being treated as passive".

Bugfix to prevent error in slimscroll. 

---

bin/commands/countly.sh

You can upgrade to Enterprise Edition from Community Edition with Enterprise Edition package in root directory of Countly & `countly upgrade ee` command.

Add ability to upgrade Community Edition to Enterprise Edition

---

bin/scripts/checking_versions.js

This PR contains 2 changes:
1. Version matching regular expression
2. Version sorting
The current expression allows pretty much any version, whereas some script comment clearly stats that version numbers must not be larger than 2 digits.
Considering the following test code:
```
const pattern = new RegExp(/^(([0-9])*\.)*[0-9]*$/);
const tests = [
'9',
'9.3',
'16',
'16.1',
'16.01',
'16.1.2',
'16.1.2.3',
'16.11.22.33',
'16.111',
'16.1.222.3',
'16.',
'16..',
'16..123456',
'16.1.2.3.4.5.6.7',
];
for (const t of tests) {
console.log(`${t}: ${pattern.test(t)}`);
}
```
Hereafter is the result with current pattern:
```
9: true
9.3: true
16: true
16.1: true
16.01: true
16.1.2: true
16.1.2.3: true
16.11.22.33: true
16.111: true
16.1.222.3: true
16.: true
16..: true
16..123456: true
16.1.2.3.4.5.6.7: …
```

Fixed version matching regular expression and version sorting

---

bin/scripts/add_indexes.js

The termination callback does not rely on a human-written number anymore but the amount of parallel is now predictable and computable ahead of time, before any job start.
Jobs can be synchronous, it remains safe.

Made parallel add index more reliable

---

plugins/views/frontend/public/javascripts/countly.views.js

Avg Scroll column should be invisible for mobile app types

[SERVER-1471] Analytics > Views > hide avg scroll for mobile

---

bin/scripts/checking_versions.js

This fix makes sure `15` is equal to `15.0` and not considered smaller.
In term of versions sorting, it's not a big deal and the old code does not break ordering, but it's better to be accurate.
Sorry for introducing this issue in my previous PR.

Made versions comparison mathematically correct

---

plugins/crashes/frontend/public/javascripts/countly.views.js

Fixed a bug where the crash manipulation menu chevron wasn't updated if you clicked somewhere else on the screen to close it.

[crashes] fixed crash menu arrow

---

api/utils/render.js

I installed Countly on my own Archlinux server, and didn't want to go through the hassle of dealing with compiling/installing Puppeteer. Since I noticed that it wasn't that essential to use Puppeteer, I removed it from my own package.json. I figured this would be a nice RT check: if the user (server admin / developer) has opted out of installing Puppeteer, then simply ignore the functionality which depends on Puppeteer.

gracefully skip puppeteer if not installed

---

bin/config/nginx.server.ssl.conf

Updated `ssl_ciphers` due to latest security tests.

NGINX SSL update

---

bin/scripts/check-translations.js

This tool helps to check the state of translations for a given container.
It tells if a language has missing translations, or translations that do not exist in the base language (English).
It also helps finding duplicated keys.
Transifex can tell us the latest state of translations, but can't tell us the state at a given time. When a container is built, the translations are baked in, and if we need to update the translations at a later time, we can't use Transifex anymore because the latest state may be different and mismatch the container's one.
This tool works with the `.properties` files so it's in the state the container is, at the time it was built. Then we can easily find missing translations and update our container through …

Added a tool to check the state of localization in a container

---

frontend/express/public/javascripts/countly/countly.views.js

if the application is a newly created application with more than five events, this application should be displayed under normal conditions, but `Job did not run yet` because it did not expire after `24 hours` and `there is no data`. In such a situation; TopEvents will not be updated when switching between applications.

[UI] TopEvents bug fix

---

plugins/dbviewer/frontend/public/templates/dbviewer.html

The problem is browser autofill and autocompleting input on `master` and `next` server.  The tried  `autocomplete=nope|new|off` solutions do not work on the `Chrome Version 80.0.3987.149 (Official Build) (64-bit)` So, I have a simple inline JavaScript code and it's fixed this issue. And maybe it can work in the next versions, we should not delete autocomplete.

[UI][DB VIEWER] Forms Autocomplete

---

plugins/populator/frontend/public/javascripts/countly.models.js

- fixed events with just names (nothing else) being culled when being sent to the API
- removed adding duration to events without duration in their templates (except internal view events)

Populator templates hotfixes

---

plugins/pluginManager.js

As we discussed, here are the changes:
1. The call to `register`ed function now supports the cases where it throws synchronously.
I'm not sure if the `if (promise) { used = true; }` should go in the `try` block to not set to true in case of error. Let me know.
2. Result of settled promises is not reduced to their value anymore, giving more control to the caller of `dispatch` for error handling.

Made pluginsManager's dispatch function more error resilient

---

plugins/pluginManager.js

@iartem (CC @ar2rsawseen)
Hi Artem, I would like to make a suggestion for a different way to handle Bluebird non-standard `Promise.allSettled`.

Fix Bluebird Promise.allSettled non-standard polyfill

---

frontend/express/public/javascripts/countly/countly.views.js
frontend/express/public/localization/dashboard/dashboard.properties

Fixed by changing all named events to N events in case there is text length limit reached (Currently length is 100). In case single event name is to long it is cropped and added ... at the end of it.

[SERVER-1845] Bugfix. Deleting multiple events Confirmation button is of screen.

---

api/jobs/topEvents.js

The issue with Top Events 24 Hours data was resolved by adding a new parameter of `action`.

[SERVER-1896][API]

---

plugins/systemlogs/api/api.js

Error: Unhandled rejection (reason: TypeError: Cannot read property 'before' of null

[SERVER-1918] Bugfix

---

README.md

Hey! I was just trying to get the project running and reading some docs, so I could tackle the initial exercise later.
It seems the link to the Docker image is incorrect though, it should be `/r/`, not `/u/`. :thinking: 
This PR just corrects that so users get taken to the page they expect.

Fix Link to Docker Hub Image

---

plugins/views/api/api.js

(Messed up view name on bounce and exit. Resulted two seperate records for view properties)

Bugfix. Views.Postprocessing.

---

api/lib/countly.common.js

quick fix to helper functions that make period objects to make moment stop formatting 2020 w53 as 2020 w1 and format it to 2021 w1 instead

[api] use week years for week-long ticks

---

plugins/systemlogs/api/api.js
plugins/systemlogs/frontend/app.js
plugins/systemlogs/frontend/public/javascripts/countly.views.js
plugins/systemlogs/frontend/public/localization/systemlogs.properties

By adding "Disable IP Tracking" option, ip tracking is prevented when settings are changed and login/logout operations.

SERVER-2285: Audit Logs add option not to record and show IP address

---

frontend/express/public/javascripts/countly/vue/components/dropdown.js
frontend/express/public/stylesheets/styles/blocks/_dropdown.scss

What's different?
- `fields[].items[]` property names follow `el-option` prop names so `label` actually maps to `label` and `key` maps to rest of the option props used internally (`key` and `value`).
- Using `fields[].options` instead of `fields[].items` allows you to use `cly-select-x` instead of `el-select`.
- `resetLabel` is now a prop in case someone needs to change it for their use.
- You can now just use `v-model` with the component and have it actually work correctly right away instead of having to mess with setters in the parent component.
- Its SCSS is no longer all wack with mixed/incorrect indentation.
- Worryingly vague `controls` class renamed to more BEM-y `cly-multi-select__controls`.
What can be improved?
- `resetLabel` and `title` props' default values should be replaced …

[frontend] derived saner version of cly-fields-select called cly-multi-select

---

frontend/express/public/javascripts/countly/vue/components/helpers.js

Fix: emit save event for disabled button only when emitSaveWenDisabled is true.
NOTE: this property is needed to run validator whenever user selects save.

fix: Emit save event for disabled button only when emitSaveWhenDisabled is true

---

frontend/express/public/javascripts/countly/vue/templates/datatable.html
frontend/express/public/stylesheets/styles/blocks/_table.scss

loading icon and loading text look bad together, so loading text removed, only icon will appear.

Empty slot CSS changes.

---

frontend/express/public/core/session-overview/stylesheets/_main.scss
frontend/express/public/stylesheets/styles/states/_state.scss
frontend/express/public/stylesheets/vue/clyvue.scss

the spaces looks aligned in my editor(vscode), I don't understand why they look so irregular here, but I can check if you wish.

Trend icons font weight changes

---

plugins/push/api/send/data/message.js

Use a mongodb object id format when creating test message used
to verify a platform key. Otherwise, a message validation error is thrown.

fix: Validation error when updating push notification configuration

---

frontend/express/public/javascripts/countly/vue/components/datatable.js

Sometimes when the columns are created dynamically, selected column may have a column, which will not be generated on the next time the table loads.

ensure undefined is not in dynamic cols

---

plugins/push/api/send/audience.js
plugins/push/frontend/public/javascripts/countly.models.js

Stringify queryObject in the client side instead of doing it on the server side.

fix: drill queryObject parameter error

---

frontend/express/public/core/user-analytics-overview/javascripts/countly.views.js
plugins/systemlogs/api/api.js

Bugfix. Dashboards widgets. Prevent not showing template for analytics users in case of invalid breakdown value.
null check for systemlogs error:
TypeError: Cannot read property 'email' of undefined
at recordAction (/home/countly/countly/plugins/systemlogs/api/api.js:343:22)

Fixes. Dashboards. Systemlogs.

---

plugins/times-of-day/frontend/public/javascripts/countly.models.js
plugins/times-of-day/frontend/public/javascripts/countly.views.js
plugins/times-of-day/frontend/public/templates/times-of-day-widget.html

Use backward compatible period values for times of day widget.
Remove height property from times of day widget scatter chart.

Fix/times of day dashboard properties,and height error

---

plugins/push/frontend/public/javascripts/countly.models.js
plugins/push/frontend/public/localization/push.properties
plugins/push/frontend/public/templates/common-components.html

Remove internationalization for error codes. Instead, use it only
for error descriptions when they are found otherwise display empty string

fix: Error code internationlization

---

plugins/push/frontend/public/javascripts/countly.models.js

Use label value instead of actual user property value.

fix: User property label error on  essage editor

---

frontend/express/public/core/platform/templates/platform.html
plugins/browser/frontend/public/templates/browser.html
plugins/density/frontend/public/templates/density.html

If the number of items is less than 4 (for example in case of 2), no data is displayed on the metric cards (even if there are versions).
This control has been added to the metric cards on the distribution.

Added control for no data case

---

plugins/logger/frontend/public/javascripts/countly.views.js
plugins/logger/frontend/public/templates/logger.html

Currently, request logs table row can only be expanded by clicking the tiny little triangle icon on the left side.

[SER-79] Update request logs table row

---

plugins/systemlogs/frontend/public/javascripts/countly.views.js
plugins/systemlogs/frontend/public/templates/logs.html

Currently, audit logs table row can only be expanded by clicking the tiny little triangle icon on the left side.

[SER-84] Update audit logs table row

---

plugins/remote-config/frontend/public/javascripts/countly.views.js
plugins/remote-config/frontend/public/templates/parameters.html

Currently, remote config parameters table row can only be expanded by clicking the tiny little triangle icon on the left side.

[SER-82] Update remote config parameters table row

---

plugins/compliance-hub/frontend/public/javascripts/countly.views.js
plugins/compliance-hub/frontend/public/templates/consentHistory.html

Currently, consent history table row can only be expanded by clicking the tiny little triangle icon on the left side.

[SER-83] Update consent history table row

---

plugins/sources/frontend/public/javascripts/countly.views.js
plugins/sources/frontend/public/templates/sources-tab.html

Currently, sources table row can only be expanded by clicking the tiny little triangle icon on the left side.

[SER-80] Update sources table row

---

api/parts/data/exports.js
plugins/dbviewer/frontend/public/javascripts/countly.views.js

Since mongodb driver update needed to  restructure code when working with cursor.stream();
[SER-149] DB Viewer cannot export data when data is filter is applied. Fixed UI bug for that.
[SER-149]: https://countly.atlassian.net/browse/SER-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SER-149] DB Viewer cannot export data when data is filter is applied

---

plugins/density/api/api.js

Bug would happen if platform name starts with different letter that its short version.

bugfix for storing densities in some cases.

---

frontend/express/public/javascripts/countly/vue/components/input.js
frontend/express/public/javascripts/countly/vue/templates/datatable.html

datatable column filter
The screenshots below are for checking this part https://github.com/Countly/countly-server/blob/master/frontend/express/public/javascripts/countly/vue/templates/selectx.html#L46-L69. To make sure that the header is displayed correctly if at least one item on the header exists.
select-x with title prop
select-x with header slot
select-x with action slot
select-x with show-selected-count prop
select-x with show-search prop

[core] Fix select x header condition and datatable column filter

---

frontend/express/public/javascripts/countly/vue/components/date.js

This problem can be seen by selecting the date 90 days on the retention plugin.

[SER-139]: Fixed the date constraint that does not include the last day.

---

plugins/crashes/frontend/public/javascripts/countly.models.js
plugins/crashes/frontend/public/javascripts/countly.views.js
plugins/crashes/frontend/public/stylesheets/crashes.scss
plugins/crashes/frontend/public/templates/crashgroup.html

Some updates for crashgroup detail page
- Add stack trace level  … menu and put options like Download stack trace and Upload symbol under that menu
- Add Symbolicate/resymbolicate action under the same menu
- Add toggling Symbolicated/Unsymbolicated stack trace
- Make sure multiple thread crashes are shown correctly

[SER-199] Crash group detail page update

---

plugins/crashes/frontend/public/javascripts/countly.views.js
plugins/crashes/frontend/public/templates/binary-images.html

- In binary image screen -> Add symbols button should prefill fields when it opens the form
- In binary image screen -> should indicate which symbols already provided by removing Add symbols button
- In binary image screen -> table header is broken, should be fixed (note: table header is too cramped and has fixed height so the content is moved to page header to avoid breaking the layout)

[SER-196] Update binary image page

---

api/utils/requestProcessor.js
plugins/logger/frontend/public/templates/logger.html

Backward compatibility.
checksum_calt could be stored under app.salt.
UI fix. Showing cancelation+reason in request logs.

BUG - salt is not working. Requests are not being rejected. showing cancellation error on request logs

---

plugins/populator/frontend/public/stylesheets/populator.scss

Fixed the "more-options" element not appearing in the table when the height is increased while listing Populator templates (it can be seen when selecting more than 10 entries for paging).

Populator templates datatable's alignment issue.

---

plugins/crashes/frontend/public/javascripts/countly.query.builder.crashgroups.js

`os` is stored as string in mongo. In the current query builder the query for `os` is like `{"os.os_name": {"$exists": true}}`. This query does not work for string and that is why it is giving the wrong search results.
Removing `os` from `indexedProps` will turn the query for `os` to something like `{"os": {"$in": ['os_name']}}`. This query works for string and it will give the correct search results.

[SUP-13] [crashes] Fix crashgroup query builder

---

api/utils/requestProcessor.js

New UI stores in varable 'salt'. If nothing stored - fall back to checksum_salt(old version)

fix for salt.

---

frontend/express/public/javascripts/countly/vue/components/input.js
plugins/crashes/frontend/public/javascripts/countly.views.js

- Fix matching method in searchable options mixin. The options are not always a string
- Fix app version filter in query builder. Replace data source for app version to vuex

[SUP-24] [crashes] Fix app version in query builder

---

Dockerfile-api
Dockerfile-centos-api
Dockerfile-centos-frontend
Dockerfile-frontend

- CentOS images updated to 8
- Ubuntu images migrated to 'bullseye-slim' versions with only required OS dependencies

Decrease vulnerabilities on Dockerfiles

---

api/parts/mgmt/apps.js
frontend/express/app.js
test/3.api.write/8.checksums.js

(To prevent errors for instances with bady saved data, because of previous bugs on edit app form)

Cleaning up checksum_salt on update, showing value on fetch.

---

plugins/crashes/frontend/public/javascripts/countly.models.js
plugins/crashes/frontend/public/javascripts/countly.views.js

Multiple exists queries to mongodb has to be 'or'ed
`{$or: [{field1: {$exists: true}}, {field2: {$exists: true}}]}`
instead of
`{field1: {$exists: true}, field2: {$exists: true}}`

[SUP-28] [crashes] Modify exists queries to get correct result from db

---

api/utils/taskmanager.js

Reason for this: Many clients don't set rights to allow THAT, so their logs are filled with error messages, which is confusing.

Do not record failure to create operation id as error in taskmanager,but as debug.

---

frontend/express/public/javascripts/countly/vue/components/vis.js

Sometimes it does not add overlay on mounted function so it causes a tooltip issue and brokes the chart. Adding overlay was moved to onClick()

Graph-Notes: Tooltip fixes

---

frontend/express/public/javascripts/countly/countly.helpers.js
frontend/express/public/javascripts/countly/vue/core.js

This pr adds a new popup dialog that can be used to block the whole screen.
This dialog is added on the core level so it can be activated from any plugin on the front end.

[core] Blocker dialog for license

---

frontend/express/public/javascripts/countly/vue/components/nav.js

uses `v-if` to only display tab, if numbers of tabs > 1

[SER-344] Don't display the vue-tabs element in the view when there is only 1 option

---

plugins/crashes/frontend/public/javascripts/countly.views.js

Add crash filter to the url so it is still available after visiting crash detail page. Just like in user profiles.

[SER-365] Preserve crash filter

---

frontend/express/public/javascripts/countly/vue/components/vis.js

maintains unique properties inside deep nested object instead of replacing it with the last one in array.

[SER-440] default-properties-are-not-being-applied-on-dual-axis-charts

---

plugins/plugins/api/api.js

`internal-events` endpoint is used somewhere that is not only for global admin. So the access right has to be adjusted.

[plugins] Update internal-events endpoint access right

---

plugins/crashes/frontend/public/templates/overview.html

This margin is to prevent table footer being blocked by action bar when crash item is selected.

[SUP-34] [crashes] Add margin to data table in crash overview page

---

bin/upgrade/22.09/scripts/upgrade_crashgroup_app_version.js
frontend/express/public/javascripts/countly/vue/components/datatable.js
plugins/crashes/api/api.js
plugins/crashes/api/parts/version.js
plugins/crashes/frontend/public/javascripts/countly.models.js
plugins/crashes/frontend/public/javascripts/countly.views.js
plugins/crashes/frontend/public/templates/crashgroup.html
plugins/crashes/frontend/public/templates/overview.html

This pr adds a new field to `crashgroup` collection based on `crashgroup.latest_version`. This new field can be used to sort crashgroup in a numerically correct way.
The same sorting method is also used for `crashes` but only on the front-end side.

[SER-360] Correct crash sorting by app version

---

frontend/express/public/javascripts/countly/vue/components/sidebar.js

The call to `sortBy` method causes error when `AppsMixin` is included into a component that does not have `sortBy` method. So move `sortBy` method into `AppsMixin`.

[SER-528] Move sortBy method into AppsMixin

---

frontend/express/public/javascripts/countly/vue/components/datatable.js
frontend/express/public/javascripts/countly/vue/components/input.js

[[fix] table reorder is reflected w/o refresh](https://github.com/Countly/countly-server/commit/2787392a7b5a6e4c96865e80c45f76ae15e044b4)

[SER-337] Store table column order settings in database

---

plugins/compliance-hub/frontend/public/javascripts/countly.models.js
plugins/compliance-hub/frontend/public/javascripts/countly.views.js

This will fix consent history filter in compliance-hub

[SER-510] [compliance-hub] Use 'change' instead of 'after' for filter

---

.shellcheckrc
bin/commands/scripts/shellcheck.sh

There is inconsistency about reading excludes from rc file between versions, using arguments for excludes as workaround.
ref: https://github.com/koalaman/shellcheck/issues/2534

Migrate shellcheck rules from rc file to args

---

plugins/crashes/api/api.js
plugins/crashes/frontend/public/javascripts/countly.models.js
plugins/crashes/tests.js

- Fix binary images not saved correctly in crashes document
Should be `{"binary_images": "content"}` instead of `{binary_images: "undefined-undefined": "content"}`
- Fix `Show binary images` action not showing in crashgroup dropdown

[SER-598] Crash binary image fixes

---

bin/docker/k8s/countly-api.yaml
bin/docker/k8s/countly-ingestion-ingress-baremetal_setup.yaml
bin/docker/k8s/countly-ingestion-ingress-gce.yaml
bin/docker/k8s/countly-ingestion-ingress.yaml
bin/docker/k8s/countly-ingestion.yaml
bin/docker/k8s/mongo/mongo-single.yaml
bin/docker/k8s/mongo/values.yaml

- Service & Deployment file added for Ingestion based routing
- Ingress file created for GCE,Cloud & Baremetal to match ingestion based routing
- upgraded Mongodb versions for standalone & replicaset setup of k8's
- upgraded countly Image version in api, frontend & ingestion deployment files
- updated delay & timeout period for Readiness probe in all deployment
- updated Plugins to match current list of supported plugins.

Added service,deployment & ingress files for ingestion traffic routing

---

plugins/crashes/frontend/public/templates/crashgroup.html

When symbolicated stacktrace is empty, stacktrace section is not shown in crashgroup detail page. This pr fix the condition check for stacktrace section so that it will still be shown when symbolicated stacktrace is empty.

[SER-617] [crashes] Fix stacktrace section condition check

---

bin/upgrade/23.03/scripts/rebuild_member_permission.js

This pr adds a script that will rebuild member permission.
Previously when a group is deleted or updated, that group member permissions are not updated correctly. This script can be used to repair those incorrect permission.

[SER-692] Add rebuild member permission script

---

plugins/crashes/api/api.js
plugins/crashes/frontend/public/localization/crashes.properties

Crashgroup keeps latest crash id as lrid in document. Currently when receiving new crash with same app version as the latest crash, lrid is not updated to the incoming crash id. This pr adds a setting that enables updating latest crash id even if incoming crash app version is the same as the latest crash app version.

[SER-631] [crashes] Update latest crash id in crashgroup even if new crash app version is the same as the last

---

plugins/data-manager/frontend/public/javascripts/countly.views.js
plugins/data-manager/frontend/public/templates/events-default.html

- Delete drill_meta of an event by passing `key || e || name` , so it no longer appears in data manager->events.
- blank list of selected events in delete popup fixed:

[SER-708] Issue while deleting event

---

frontend/express/public/core/user-management/javascripts/countly.views.js

[Fix] CRUD Checkboxes are automatically toggled after permission is set by type or feature

User Management Fix

---

api/parts/mgmt/users.js
test/2.api/05.update.user.js

When a member is edited through API, the member permission is broken.
This is because the API can still receive old permission parameters but it does not generate the correct permission object from those parameters (related doc [/i/users/update](https://api.count.ly/reference/iusersupdate) ).
This pr updates the API so that it can generate correct permission based on the old permission parameters.

[SER-750] Set member permission when editing

---

api/parts/mgmt/users.js

handle permission object with missing _CRUD_, ex: `{ _: { a: [], u: [] } }`

Handle partial permission object in depCheck

---

bin/upgrade/DEV/scripts/remove_deleted_recors_from_widgets.js
plugins/dashboards/api/api.js
plugins/dashboards/api/parts/dashboards.js

This script detects also deleted funnels & formulas data to remove from widgets [SER-688] [SER-689]
[SER-688]: https://countly.atlassian.net/browse/SER-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SER-689]: https://countly.atlassian.net/browse/SER-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SER-690] Delete dashboard widgets if a related Drill query is deleted

---

api/utils/countly-request/index.js

fileFormUpload was called when request.form exists. This was not correct. form can exists but it may not be file upload. This was breaking AD Plugin

[SER-760] request form bugfix

---

plugins/server-stats/api/api.js

When counting data points . If in request event segment count =2, it still has to count as single data point

[bugfix][data points]

---

frontend/express/public/javascripts/countly/vue/components/helpers.js

- adds optional param `goTo` which can be used to redirect user when displaying notification

[SER-1054] Add link to cly-notification

---

bin/countly.install_rhel.sh

1. Installer script switched to use DNF, because it is default package manager since RHEL 8.0
2. ipa-gothic-fonts is available for both supported rhel distros, so no conditions are needed

Minor improvements for RHEL installer

---

bin/scripts/member-managament/delete_members_with_string_id.js

This script deletes user(s) with invalid `_id` (of type string instead of ObjectId).
It either takes a list of emails to delete users, or we can directly delete all invalid users.

[SER-1141] Delete Invaild members with string ID

---

api/parts/data/events.js

Changes for this bug report,
https://countly.slack.com/archives/C0469N7GX24/p1710826591407139
Tested for requests with events keys,
- events=[{"key":"1"}]
- events=[{"key":1}]
- events=[{"key":null}]
- &events=[{"key":{"object":"ob"}}]

Fixed TypeError currEvent.key.indexOf is not a function

---

frontend/express/public/javascripts/countly/vue/components/helpers.js

In next branch, cly-event-select component works broken in some places such as funnels drawer and cohorts drawers.
There is a default 400px from cly-select-x. In most places, content does not fit into the component because width value is not given when calling component. Therefore, I added 'fit-content' as a default value in prop. 
The calculation, for this [task](https://countly.atlassian.net/browse/SER-777),  in created() has been removed as unnecessary. And I also checked if it affected place where it was used in this task.
Also I removed computedWidth field as unnecessary again(https://github.com/Countly/countly-server/commit/cb71ac2e1b3eba4320a9fdc2ef966e6c7a7efc1f) It won't give error anymore as we removed the assignment width prop in created()
please contact me if you have any …

[component-ui-fix] Width of cly-event-select component is fixed

---

plugins/alerts/frontend/public/javascripts/countly.views.js

data types which is the plugins that belong to the enterprise version are not listed on the community edition version anymore

[SER-1444] update on the alert data type options for CE

---

plugins/crashes/api/parts/stacktrace.js
plugins/crashes/tests.js

Flutter stacktrace is formatted like
```
java.lang.Exception: IntegerDivisionByZeroException
--> there's an extra newline here
#0      int.~/ (dart:core-patch/integers.dart:30:7)
#1      etc...
--> another extra newline here
at ly.count.dart.countly_flutter.CountlyFlutterPlugin.onMethodCall(CountlyFlutterPlugin.java:394)
```
Because of the extra newline it's being treated as multithread. But it's not actually multithreaded so it's not processed correctly by the backend and hence it's not showing up in the frontend.
This pr adds detection for flutter stacktrace so that it can be processed correctly and be shown in the frontend. 
Note: The extra newline is actually coming from sdk, so in the future the sdk should be updated to  remove the extra newline.

[SER-1088] Flutter stacktrace

---

api/utils/requestProcessor.js
api/utils/rights.js
plugins/dbviewer/api/api.js
plugins/dbviewer/frontend/public/javascripts/countly.views.js
plugins/dbviewer/frontend/public/localization/dbviewer.properties
plugins/dbviewer/frontend/public/templates/aggregate.html

* Prevent running aggregation stages in aggregation views for users which are not global admin.
* Show events_data and drill_events collections with filtered app data based on user rights

[SER-2122] Dbviewer improvements

---

CHANGELOG.md
plugins/dashboards/README.md
plugins/dashboards/frontend/public/javascripts/countly.views.js

Fix: issue where dashboard widgets go into single column when refresh happens in responsive mobile view.
And request flowchart

Fix: issue where dashboard widgets go into single column 

---

bin/upgrade/24.12/upgrade.mongo.70.sh
bin/upgrade/24.12/upgrade_db.sh
bin/upgrade/24.12/upgrade_fs.sh

- Added step to disable/comment out journal: enabled: true in mongod.conf as its deprecated post mongo 6
- Fixed version info in both fs & db script
- As journey_engine plugin is dependent on content plugin, ammended the steps to install content plugins first.

fixed mongo7 and 2412 upgrade scripts

---

CHANGELOG.md
plugins/star-rating/frontend/public/templates/drawer.html

This fixes a bug where cohort segmentation has to be filled in when previously it does not have to

[star-rating] Add ignore existing cohort prop to drawer

---

frontend/express/public/javascripts/countly/vue/components/content.js
frontend/express/public/javascripts/countly/vue/templates/content/UI/content-sidebar-input.html
frontend/express/public/stylesheets/vue/clyvue.scss

This is required to fix [[SER-2150]](https://countly.atlassian.net/browse/SER-2150)
[SER-2150]: https://countly.atlassian.net/browse/SER-2150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] Add suffix to input number

---

frontend/express/public/javascripts/countly/vue/components/content.js
frontend/express/public/javascripts/countly/vue/templates/UI/option-swapper.html
frontend/express/public/stylesheets/vue/clyvue.scss

This complements [[SER-2143] Position options should be active according to the Devices](https://github.com/Countly/countly-enterprise-plugins/pull/1629)
[SER-2143]: https://countly.atlassian.net/browse/SER-2143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] Add disabled state to option swapper

---

api/jobs/topEvents.js

- call `done` after the job is complete, instead of as soon as job is started
- use `findOneAndReplace`, instead of calling `delete` and then waiting for the job to complete to `insert` new data (now user will see previous data while job is running, instead of no data)

[TopEventsJob] Job Improvements

---

frontend/express/public/javascripts/countly/vue/components/date.js
frontend/express/public/javascripts/countly/vue/templates/datepicker.html

If "isFuture" prop is true, disable past time slots when the date is selected is today. 
for [reference](https://element.eleme.io/#/en-US/component/time-picker#timepicker)

[SER-2207] User can create journey with past time.

---

CHANGELOG.md
frontend/express/public/javascripts/countly/vue/components/helpers.js
frontend/express/public/stylesheets/vue/clyvue.scss

Problem:
The events selected in the cly-event-select component are not listed again after the page is refreshed
Solution: Fetched available events asynchronously to ensure data is loaded before rendering the component and added a loading panel for waiting time

Events are not listed in the cly-event-select component

---

frontend/express/public/javascripts/countly/vue/templates/drawer.html

While creating the survey, if the user clicks on the "+Add Condition" button to add User Behavior Segmentation, the "Complete" button on the Review page changes to "Next step".

[SER-2235] - Save button naming in survey drawer

---

bin/countly.install_ubuntu.sh

Changes prevents the "gpg: cannot open '/dev/tty'" error that occurred during reinstallation, fix makes the script check for existing security keys first and added flags to run non-interactively. Tested the changes with both fresh install and reinstall.

made node GPG key install idempotent to avoid re-download errors
